version: "2"

linters:
  enable:
    - govet
    - ineffassign
    - staticcheck
    - misspell
    - unconvert
    - unparam

linters-settings:
  gosec:
    excludes:
      - G115  # integer overflow (false positives in proto code)

issues:
  exclude-dirs:
    - vendor
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - unparam
