// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: analytics/v1/analytics.proto

package analyticsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PredefinedPeriod int32

const (
	PredefinedPeriod_PERIOD_UNSPECIFIED PredefinedPeriod = 0
	PredefinedPeriod_PERIOD_DAY         PredefinedPeriod = 1 // сегодня
	PredefinedPeriod_PERIOD_WEEK        PredefinedPeriod = 2 // текущая неделя (Пн–Вс)
	PredefinedPeriod_PERIOD_MONTH       PredefinedPeriod = 3 // текущий месяц
	PredefinedPeriod_PERIOD_ALL         PredefinedPeriod = 4 // за всё время
)

// Enum value maps for PredefinedPeriod.
var (
	PredefinedPeriod_name = map[int32]string{
		0: "PERIOD_UNSPECIFIED",
		1: "PERIOD_DAY",
		2: "PERIOD_WEEK",
		3: "PERIOD_MONTH",
		4: "PERIOD_ALL",
	}
	PredefinedPeriod_value = map[string]int32{
		"PERIOD_UNSPECIFIED": 0,
		"PERIOD_DAY":         1,
		"PERIOD_WEEK":        2,
		"PERIOD_MONTH":       3,
		"PERIOD_ALL":         4,
	}
)

func (x PredefinedPeriod) Enum() *PredefinedPeriod {
	p := new(PredefinedPeriod)
	*p = x
	return p
}

func (x PredefinedPeriod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PredefinedPeriod) Descriptor() protoreflect.EnumDescriptor {
	return file_analytics_v1_analytics_proto_enumTypes[0].Descriptor()
}

func (PredefinedPeriod) Type() protoreflect.EnumType {
	return &file_analytics_v1_analytics_proto_enumTypes[0]
}

func (x PredefinedPeriod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PredefinedPeriod.Descriptor instead.
func (PredefinedPeriod) EnumDescriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{0}
}

type GetBarberStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BarberId      string                 `protobuf:"bytes,1,opt,name=barber_id,json=barberId,proto3" json:"barber_id,omitempty"`
	Period        *Period                `protobuf:"bytes,2,opt,name=period,proto3" json:"period,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBarberStatsRequest) Reset() {
	*x = GetBarberStatsRequest{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBarberStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBarberStatsRequest) ProtoMessage() {}

func (x *GetBarberStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBarberStatsRequest.ProtoReflect.Descriptor instead.
func (*GetBarberStatsRequest) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *GetBarberStatsRequest) GetBarberId() string {
	if x != nil {
		return x.BarberId
	}
	return ""
}

func (x *GetBarberStatsRequest) GetPeriod() *Period {
	if x != nil {
		return x.Period
	}
	return nil
}

type Period struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Period_Preset
	//	*Period_Custom
	Kind          isPeriod_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Period) Reset() {
	*x = Period{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Period) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Period) ProtoMessage() {}

func (x *Period) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Period.ProtoReflect.Descriptor instead.
func (*Period) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *Period) GetKind() isPeriod_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Period) GetPreset() PredefinedPeriod {
	if x != nil {
		if x, ok := x.Kind.(*Period_Preset); ok {
			return x.Preset
		}
	}
	return PredefinedPeriod_PERIOD_UNSPECIFIED
}

func (x *Period) GetCustom() *DateRange {
	if x != nil {
		if x, ok := x.Kind.(*Period_Custom); ok {
			return x.Custom
		}
	}
	return nil
}

type isPeriod_Kind interface {
	isPeriod_Kind()
}

type Period_Preset struct {
	Preset PredefinedPeriod `protobuf:"varint,1,opt,name=preset,proto3,enum=analytics.v1.PredefinedPeriod,oneof"`
}

type Period_Custom struct {
	Custom *DateRange `protobuf:"bytes,2,opt,name=custom,proto3,oneof"`
}

func (*Period_Preset) isPeriod_Kind() {}

func (*Period_Custom) isPeriod_Kind() {}

type DateRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"` // YYYY-MM-DD (inclusive)
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`     // YYYY-MM-DD (inclusive)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DateRange) Reset() {
	*x = DateRange{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DateRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DateRange) ProtoMessage() {}

func (x *DateRange) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DateRange.ProtoReflect.Descriptor instead.
func (*DateRange) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *DateRange) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *DateRange) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type BarberStatsResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	BarberId   string                 `protobuf:"bytes,1,opt,name=barber_id,json=barberId,proto3" json:"barber_id,omitempty"`
	PeriodFrom string                 `protobuf:"bytes,2,opt,name=period_from,json=periodFrom,proto3" json:"period_from,omitempty"` // YYYY-MM-DD (resolved)
	PeriodTo   string                 `protobuf:"bytes,3,opt,name=period_to,json=periodTo,proto3" json:"period_to,omitempty"`       // YYYY-MM-DD (resolved)
	// Числовые показатели
	ClientsServed     int64         `protobuf:"varint,4,opt,name=clients_served,json=clientsServed,proto3" json:"clients_served,omitempty"` // COUNT bookings WHERE status = completed
	TotalRevenue      int64         `protobuf:"varint,5,opt,name=total_revenue,json=totalRevenue,proto3" json:"total_revenue,omitempty"`    // SUM price WHERE status = completed (руб.)
	HoursWorked       float64       `protobuf:"fixed64,6,opt,name=hours_worked,json=hoursWorked,proto3" json:"hours_worked,omitempty"`      // SUM рабочих часов из расписания
	AverageCheck      float64       `protobuf:"fixed64,7,opt,name=average_check,json=averageCheck,proto3" json:"average_check,omitempty"`   // total_revenue / clients_served
	BookingsTotal     int64         `protobuf:"varint,8,opt,name=bookings_total,json=bookingsTotal,proto3" json:"bookings_total,omitempty"`
	BookingsCompleted int64         `protobuf:"varint,9,opt,name=bookings_completed,json=bookingsCompleted,proto3" json:"bookings_completed,omitempty"`
	BookingsCancelled int64         `protobuf:"varint,10,opt,name=bookings_cancelled,json=bookingsCancelled,proto3" json:"bookings_cancelled,omitempty"`
	BookingsNoShow    int64         `protobuf:"varint,11,opt,name=bookings_no_show,json=bookingsNoShow,proto3" json:"bookings_no_show,omitempty"`
	OccupancyRate     float64       `protobuf:"fixed64,12,opt,name=occupancy_rate,json=occupancyRate,proto3" json:"occupancy_rate,omitempty"`  // 0.0–1.0: время записей / рабочее время
	TopServices       []*TopService `protobuf:"bytes,13,rep,name=top_services,json=topServices,proto3" json:"top_services,omitempty"`          // отсортировано по count DESC
	DailyBreakdown    []*DayStat    `protobuf:"bytes,14,rep,name=daily_breakdown,json=dailyBreakdown,proto3" json:"daily_breakdown,omitempty"` // для графиков на фронте
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BarberStatsResponse) Reset() {
	*x = BarberStatsResponse{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BarberStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BarberStatsResponse) ProtoMessage() {}

func (x *BarberStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BarberStatsResponse.ProtoReflect.Descriptor instead.
func (*BarberStatsResponse) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *BarberStatsResponse) GetBarberId() string {
	if x != nil {
		return x.BarberId
	}
	return ""
}

func (x *BarberStatsResponse) GetPeriodFrom() string {
	if x != nil {
		return x.PeriodFrom
	}
	return ""
}

func (x *BarberStatsResponse) GetPeriodTo() string {
	if x != nil {
		return x.PeriodTo
	}
	return ""
}

func (x *BarberStatsResponse) GetClientsServed() int64 {
	if x != nil {
		return x.ClientsServed
	}
	return 0
}

func (x *BarberStatsResponse) GetTotalRevenue() int64 {
	if x != nil {
		return x.TotalRevenue
	}
	return 0
}

func (x *BarberStatsResponse) GetHoursWorked() float64 {
	if x != nil {
		return x.HoursWorked
	}
	return 0
}

func (x *BarberStatsResponse) GetAverageCheck() float64 {
	if x != nil {
		return x.AverageCheck
	}
	return 0
}

func (x *BarberStatsResponse) GetBookingsTotal() int64 {
	if x != nil {
		return x.BookingsTotal
	}
	return 0
}

func (x *BarberStatsResponse) GetBookingsCompleted() int64 {
	if x != nil {
		return x.BookingsCompleted
	}
	return 0
}

func (x *BarberStatsResponse) GetBookingsCancelled() int64 {
	if x != nil {
		return x.BookingsCancelled
	}
	return 0
}

func (x *BarberStatsResponse) GetBookingsNoShow() int64 {
	if x != nil {
		return x.BookingsNoShow
	}
	return 0
}

func (x *BarberStatsResponse) GetOccupancyRate() float64 {
	if x != nil {
		return x.OccupancyRate
	}
	return 0
}

func (x *BarberStatsResponse) GetTopServices() []*TopService {
	if x != nil {
		return x.TopServices
	}
	return nil
}

func (x *BarberStatsResponse) GetDailyBreakdown() []*DayStat {
	if x != nil {
		return x.DailyBreakdown
	}
	return nil
}

type TopService struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Count         int64                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`     // завершённых записей
	Revenue       int64                  `protobuf:"varint,4,opt,name=revenue,proto3" json:"revenue,omitempty"` // суммарная выручка
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopService) Reset() {
	*x = TopService{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopService) ProtoMessage() {}

func (x *TopService) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopService.ProtoReflect.Descriptor instead.
func (*TopService) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *TopService) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *TopService) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *TopService) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *TopService) GetRevenue() int64 {
	if x != nil {
		return x.Revenue
	}
	return 0
}

type DayStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"` // YYYY-MM-DD
	Clients       int64                  `protobuf:"varint,2,opt,name=clients,proto3" json:"clients,omitempty"`
	Revenue       int64                  `protobuf:"varint,3,opt,name=revenue,proto3" json:"revenue,omitempty"`
	HoursWorked   float64                `protobuf:"fixed64,4,opt,name=hours_worked,json=hoursWorked,proto3" json:"hours_worked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DayStat) Reset() {
	*x = DayStat{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DayStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DayStat) ProtoMessage() {}

func (x *DayStat) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DayStat.ProtoReflect.Descriptor instead.
func (*DayStat) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{5}
}

func (x *DayStat) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DayStat) GetClients() int64 {
	if x != nil {
		return x.Clients
	}
	return 0
}

func (x *DayStat) GetRevenue() int64 {
	if x != nil {
		return x.Revenue
	}
	return 0
}

func (x *DayStat) GetHoursWorked() float64 {
	if x != nil {
		return x.HoursWorked
	}
	return 0
}

var File_analytics_v1_analytics_proto protoreflect.FileDescriptor

const file_analytics_v1_analytics_proto_rawDesc = "" +
	"\n" +
	"\x1canalytics/v1/analytics.proto\x12\fanalytics.v1\"b\n" +
	"\x15GetBarberStatsRequest\x12\x1b\n" +
	"\tbarber_id\x18\x01 \x01(\tR\bbarberId\x12,\n" +
	"\x06period\x18\x02 \x01(\v2\x14.analytics.v1.PeriodR\x06period\"}\n" +
	"\x06Period\x128\n" +
	"\x06preset\x18\x01 \x01(\x0e2\x1e.analytics.v1.PredefinedPeriodH\x00R\x06preset\x121\n" +
	"\x06custom\x18\x02 \x01(\v2\x17.analytics.v1.DateRangeH\x00R\x06customB\x06\n" +
	"\x04kind\"/\n" +
	"\tDateRange\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\"\xd7\x04\n" +
	"\x13BarberStatsResponse\x12\x1b\n" +
	"\tbarber_id\x18\x01 \x01(\tR\bbarberId\x12\x1f\n" +
	"\vperiod_from\x18\x02 \x01(\tR\n" +
	"periodFrom\x12\x1b\n" +
	"\tperiod_to\x18\x03 \x01(\tR\bperiodTo\x12%\n" +
	"\x0eclients_served\x18\x04 \x01(\x03R\rclientsServed\x12#\n" +
	"\rtotal_revenue\x18\x05 \x01(\x03R\ftotalRevenue\x12!\n" +
	"\fhours_worked\x18\x06 \x01(\x01R\vhoursWorked\x12#\n" +
	"\raverage_check\x18\a \x01(\x01R\faverageCheck\x12%\n" +
	"\x0ebookings_total\x18\b \x01(\x03R\rbookingsTotal\x12-\n" +
	"\x12bookings_completed\x18\t \x01(\x03R\x11bookingsCompleted\x12-\n" +
	"\x12bookings_cancelled\x18\n" +
	" \x01(\x03R\x11bookingsCancelled\x12(\n" +
	"\x10bookings_no_show\x18\v \x01(\x03R\x0ebookingsNoShow\x12%\n" +
	"\x0eoccupancy_rate\x18\f \x01(\x01R\roccupancyRate\x12;\n" +
	"\ftop_services\x18\r \x03(\v2\x18.analytics.v1.TopServiceR\vtopServices\x12>\n" +
	"\x0fdaily_breakdown\x18\x0e \x03(\v2\x15.analytics.v1.DayStatR\x0edailyBreakdown\"~\n" +
	"\n" +
	"TopService\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x03R\x05count\x12\x18\n" +
	"\arevenue\x18\x04 \x01(\x03R\arevenue\"t\n" +
	"\aDayStat\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x18\n" +
	"\aclients\x18\x02 \x01(\x03R\aclients\x12\x18\n" +
	"\arevenue\x18\x03 \x01(\x03R\arevenue\x12!\n" +
	"\fhours_worked\x18\x04 \x01(\x01R\vhoursWorked*m\n" +
	"\x10PredefinedPeriod\x12\x16\n" +
	"\x12PERIOD_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"PERIOD_DAY\x10\x01\x12\x0f\n" +
	"\vPERIOD_WEEK\x10\x02\x12\x10\n" +
	"\fPERIOD_MONTH\x10\x03\x12\x0e\n" +
	"\n" +
	"PERIOD_ALL\x10\x042l\n" +
	"\x10AnalyticsService\x12X\n" +
	"\x0eGetBarberStats\x12#.analytics.v1.GetBarberStatsRequest\x1a!.analytics.v1.BarberStatsResponseBJZHgithub.com/RomanKovalev007/barber_crm/api/proto/analytics/v1;analyticsv1b\x06proto3"

var (
	file_analytics_v1_analytics_proto_rawDescOnce sync.Once
	file_analytics_v1_analytics_proto_rawDescData []byte
)

func file_analytics_v1_analytics_proto_rawDescGZIP() []byte {
	file_analytics_v1_analytics_proto_rawDescOnce.Do(func() {
		file_analytics_v1_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analytics_v1_analytics_proto_rawDesc), len(file_analytics_v1_analytics_proto_rawDesc)))
	})
	return file_analytics_v1_analytics_proto_rawDescData
}

var file_analytics_v1_analytics_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_analytics_v1_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_analytics_v1_analytics_proto_goTypes = []any{
	(PredefinedPeriod)(0),         // 0: analytics.v1.PredefinedPeriod
	(*GetBarberStatsRequest)(nil), // 1: analytics.v1.GetBarberStatsRequest
	(*Period)(nil),                // 2: analytics.v1.Period
	(*DateRange)(nil),             // 3: analytics.v1.DateRange
	(*BarberStatsResponse)(nil),   // 4: analytics.v1.BarberStatsResponse
	(*TopService)(nil),            // 5: analytics.v1.TopService
	(*DayStat)(nil),               // 6: analytics.v1.DayStat
}
var file_analytics_v1_analytics_proto_depIdxs = []int32{
	2, // 0: analytics.v1.GetBarberStatsRequest.period:type_name -> analytics.v1.Period
	0, // 1: analytics.v1.Period.preset:type_name -> analytics.v1.PredefinedPeriod
	3, // 2: analytics.v1.Period.custom:type_name -> analytics.v1.DateRange
	5, // 3: analytics.v1.BarberStatsResponse.top_services:type_name -> analytics.v1.TopService
	6, // 4: analytics.v1.BarberStatsResponse.daily_breakdown:type_name -> analytics.v1.DayStat
	1, // 5: analytics.v1.AnalyticsService.GetBarberStats:input_type -> analytics.v1.GetBarberStatsRequest
	4, // 6: analytics.v1.AnalyticsService.GetBarberStats:output_type -> analytics.v1.BarberStatsResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_analytics_v1_analytics_proto_init() }
func file_analytics_v1_analytics_proto_init() {
	if File_analytics_v1_analytics_proto != nil {
		return
	}
	file_analytics_v1_analytics_proto_msgTypes[1].OneofWrappers = []any{
		(*Period_Preset)(nil),
		(*Period_Custom)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analytics_v1_analytics_proto_rawDesc), len(file_analytics_v1_analytics_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analytics_v1_analytics_proto_goTypes,
		DependencyIndexes: file_analytics_v1_analytics_proto_depIdxs,
		EnumInfos:         file_analytics_v1_analytics_proto_enumTypes,
		MessageInfos:      file_analytics_v1_analytics_proto_msgTypes,
	}.Build()
	File_analytics_v1_analytics_proto = out.File
	file_analytics_v1_analytics_proto_goTypes = nil
	file_analytics_v1_analytics_proto_depIdxs = nil
}
