// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: booking/v1/booking.proto

package bookingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SlotStatus int32

const (
	SlotStatus_SLOT_STATUS_UNSPECIFIED SlotStatus = 0
	SlotStatus_SLOT_STATUS_FREE        SlotStatus = 1
	SlotStatus_SLOT_STATUS_BOOKED      SlotStatus = 2
	SlotStatus_SLOT_STATUS_BLOCKED     SlotStatus = 3
)

// Enum value maps for SlotStatus.
var (
	SlotStatus_name = map[int32]string{
		0: "SLOT_STATUS_UNSPECIFIED",
		1: "SLOT_STATUS_FREE",
		2: "SLOT_STATUS_BOOKED",
		3: "SLOT_STATUS_BLOCKED",
	}
	SlotStatus_value = map[string]int32{
		"SLOT_STATUS_UNSPECIFIED": 0,
		"SLOT_STATUS_FREE":        1,
		"SLOT_STATUS_BOOKED":      2,
		"SLOT_STATUS_BLOCKED":     3,
	}
)

func (x SlotStatus) Enum() *SlotStatus {
	p := new(SlotStatus)
	*p = x
	return p
}

func (x SlotStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SlotStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_booking_v1_booking_proto_enumTypes[0].Descriptor()
}

func (SlotStatus) Type() protoreflect.EnumType {
	return &file_booking_v1_booking_proto_enumTypes[0]
}

func (x SlotStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SlotStatus.Descriptor instead.
func (SlotStatus) EnumDescriptor() ([]byte, []int) {
	return file_booking_v1_booking_proto_rawDescGZIP(), []int{0}
}

type BookingStatus int32

const (
	BookingStatus_BOOKING_STATUS_UNSPECIFIED BookingStatus = 0
	BookingStatus_BOOKING_STATUS_PENDING     BookingStatus = 1
	BookingStatus_BOOKING_STATUS_COMPLETED   BookingStatus = 2
	BookingStatus_BOOKING_STATUS_CANCELLED   BookingStatus = 3
	BookingStatus_BOOKING_STATUS_NO_SHOW     BookingStatus = 4
)

// Enum value maps for BookingStatus.
var (
	BookingStatus_name = map[int32]string{
		0: "BOOKING_STATUS_UNSPECIFIED",
		1: "BOOKING_STATUS_PENDING",
		2: "BOOKING_STATUS_COMPLETED",
		3: "BOOKING_STATUS_CANCELLED",
		4: "BOOKING_STATUS_NO_SHOW",
	}
	BookingStatus_value = map[string]int32{
		"BOOKING_STATUS_UNSPECIFIED": 0,
		"BOOKING_STATUS_PENDING":     1,
		"BOOKING_STATUS_COMPLETED":   2,
		"BOOKING_STATUS_CANCELLED":   3,
		"BOOKING_STATUS_NO_SHOW":     4,
	}
)

func (x BookingStatus) Enum() *BookingStatus {
	p := new(BookingStatus)
	*p = x
	return p
}

func (x BookingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BookingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_booking_v1_booking_proto_enumTypes[1].Descriptor()
}

func (BookingStatus) Type() protoreflect.EnumType {
	return &file_booking_v1_booking_proto_enumTypes[1]
}

func (x BookingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BookingStatus.Descriptor instead.
func (BookingStatus) EnumDescriptor() ([]byte, []int) {
	return file_booking_v1_booking_proto_rawDescGZIP(), []int{1}
}

type CreateBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BarberId      string                 `protobuf:"bytes,1,opt,name=barber_id,json=barberId,proto3" json:"barber_id,omitempty"`
	ServiceId     string                 `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	ClientName    string                 `protobuf:"bytes,3,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	ClientPhone   string                 `protobuf:"bytes,4,opt,name=client_phone,json=clientPhone,proto3" json:"client_phone,omitempty"`
	TimeStart     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=time_start,json=timeStart,proto3" json:"time_start,omitempty"` // time_end вычисляется сервером из duration_minutes услуги
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookingRequest) Reset() {
	*x = CreateBookingRequest{}
	mi := &file_booking_v1_booking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookingRequest) ProtoMessage() {}

func (x *CreateBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_booking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookingRequest.ProtoReflect.Descriptor instead.
func (*CreateBookingRequest) Descriptor() ([]byte, []int) {
	return file_booking_v1_booking_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBookingRequest) GetBarberId() string {
	if x != nil {
		return x.BarberId
	}
	return ""
}

func (x *CreateBookingRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *CreateBookingRequest) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *CreateBookingRequest) GetClientPhone() string {
	if x != nil {
		return x.ClientPhone
	}
	return ""
}

func (x *CreateBookingRequest) GetTimeStart() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeStart
	}
	return nil
}

type UpdateBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	BarberId      string                 `protobuf:"bytes,2,opt,name=barber_id,json=barberId,proto3" json:"barber_id,omitempty"` // для проверки владения
	ServiceId     string                 `protobuf:"bytes,3,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	TimeStart     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=time_start,json=timeStart,proto3" json:"time_start,omitempty"` // time_end пересчитывается сервером из duration_minutes новой услуги
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBookingRequest) Reset() {
	*x = UpdateBookingRequest{}
	mi := &file_booking_v1_booking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBookingRequest) ProtoMessage() {}

func (x *UpdateBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_booking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBookingRequest.ProtoReflect.Descriptor instead.
func (*UpdateBookingRequest) Descriptor() ([]byte, []int) {
	return file_booking_v1_booking_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateBookingRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *UpdateBookingRequest) GetBarberId() string {
	if x != nil {
		return x.BarberId
	}
	return ""
}

func (x *UpdateBookingRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *UpdateBookingRequest) GetTimeStart() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeStart
	}
	return nil
}

type UpdateBookingStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	BarberId      string                 `protobuf:"bytes,2,opt,name=barber_id,json=barberId,proto3" json:"barber_id,omitempty"`            // для проверки владения
	Status        BookingStatus          `protobuf:"varint,3,opt,name=status,proto3,enum=booking.v1.BookingStatus" json:"status,omitempty"` // допустимы: CANCELLED, COMPLETED, NO_SHOW
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBookingStatusRequest) Reset() {
	*x = UpdateBookingStatusRequest{}
	mi := &file_booking_v1_booking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBookingStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBookingStatusRequest) ProtoMessage() {}

func (x *UpdateBookingStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_booking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBookingStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateBookingStatusRequest) Descriptor() ([]byte, []int) {
	return file_booking_v1_booking_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateBookingStatusRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *UpdateBookingStatusRequest) GetBarberId() string {
	if x != nil {
		return x.BarberId
	}
	return ""
}

func (x *UpdateBookingStatusRequest) GetStatus() BookingStatus {
	if x != nil {
		return x.Status
	}
	return BookingStatus_BOOKING_STATUS_UNSPECIFIED
}

type BookingIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingIdRequest) Reset() {
	*x = BookingIdRequest{}
	mi := &file_booking_v1_booking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingIdRequest) ProtoMessage() {}

func (x *BookingIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_booking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingIdRequest.ProtoReflect.Descriptor instead.
func (*BookingIdRequest) Descriptor() ([]byte, []int) {
	return file_booking_v1_booking_proto_rawDescGZIP(), []int{3}
}

func (x *BookingIdRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

type Booking struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	BarberId      string                 `protobuf:"bytes,2,opt,name=barber_id,json=barberId,proto3" json:"barber_id,omitempty"`
	ServiceId     string                 `protobuf:"bytes,3,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	ServiceName   string                 `protobuf:"bytes,4,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ClientName    string                 `protobuf:"bytes,5,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	ClientPhone   string                 `protobuf:"bytes,6,opt,name=client_phone,json=clientPhone,proto3" json:"client_phone,omitempty"`
	TimeStart     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=time_start,json=timeStart,proto3" json:"time_start,omitempty"`
	TimeEnd       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=time_end,json=timeEnd,proto3" json:"time_end,omitempty"`
	Status        BookingStatus          `protobuf:"varint,9,opt,name=status,proto3,enum=booking.v1.BookingStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Booking) Reset() {
	*x = Booking{}
	mi := &file_booking_v1_booking_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Booking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Booking) ProtoMessage() {}

func (x *Booking) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_booking_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Booking.ProtoReflect.Descriptor instead.
func (*Booking) Descriptor() ([]byte, []int) {
	return file_booking_v1_booking_proto_rawDescGZIP(), []int{4}
}

func (x *Booking) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *Booking) GetBarberId() string {
	if x != nil {
		return x.BarberId
	}
	return ""
}

func (x *Booking) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *Booking) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *Booking) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *Booking) GetClientPhone() string {
	if x != nil {
		return x.ClientPhone
	}
	return ""
}

func (x *Booking) GetTimeStart() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeStart
	}
	return nil
}

func (x *Booking) GetTimeEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeEnd
	}
	return nil
}

func (x *Booking) GetStatus() BookingStatus {
	if x != nil {
		return x.Status
	}
	return BookingStatus_BOOKING_STATUS_UNSPECIFIED
}

type BookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Booking       *Booking               `protobuf:"bytes,1,opt,name=booking,proto3" json:"booking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingResponse) Reset() {
	*x = BookingResponse{}
	mi := &file_booking_v1_booking_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingResponse) ProtoMessage() {}

func (x *BookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_booking_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingResponse.ProtoReflect.Descriptor instead.
func (*BookingResponse) Descriptor() ([]byte, []int) {
	return file_booking_v1_booking_proto_rawDescGZIP(), []int{5}
}

func (x *BookingResponse) GetBooking() *Booking {
	if x != nil {
		return x.Booking
	}
	return nil
}

// SlotsRequest — все слоты дня (для барбера, staff-эндпоинт)
type SlotsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BarberId      string                 `protobuf:"bytes,1,opt,name=barber_id,json=barberId,proto3" json:"barber_id,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"` // YYYY-MM-DD
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlotsRequest) Reset() {
	*x = SlotsRequest{}
	mi := &file_booking_v1_booking_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotsRequest) ProtoMessage() {}

func (x *SlotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_booking_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotsRequest.ProtoReflect.Descriptor instead.
func (*SlotsRequest) Descriptor() ([]byte, []int) {
	return file_booking_v1_booking_proto_rawDescGZIP(), []int{6}
}

func (x *SlotsRequest) GetBarberId() string {
	if x != nil {
		return x.BarberId
	}
	return ""
}

func (x *SlotsRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type SlotsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BarberId      string                 `protobuf:"bytes,1,opt,name=barber_id,json=barberId,proto3" json:"barber_id,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Slots         []*Slot                `protobuf:"bytes,3,rep,name=slots,proto3" json:"slots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlotsResponse) Reset() {
	*x = SlotsResponse{}
	mi := &file_booking_v1_booking_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotsResponse) ProtoMessage() {}

func (x *SlotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_booking_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotsResponse.ProtoReflect.Descriptor instead.
func (*SlotsResponse) Descriptor() ([]byte, []int) {
	return file_booking_v1_booking_proto_rawDescGZIP(), []int{7}
}

func (x *SlotsResponse) GetBarberId() string {
	if x != nil {
		return x.BarberId
	}
	return ""
}

func (x *SlotsResponse) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *SlotsResponse) GetSlots() []*Slot {
	if x != nil {
		return x.Slots
	}
	return nil
}

// FreeSlotsRequest — свободные слоты (для клиента, публичный эндпоинт)
type FreeSlotsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BarberId      string                 `protobuf:"bytes,1,opt,name=barber_id,json=barberId,proto3" json:"barber_id,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`                            // YYYY-MM-DD; если пусто — ближайший доступный день
	ServiceId     string                 `protobuf:"bytes,3,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"` // опционально: фильтр по длительности услуги
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FreeSlotsRequest) Reset() {
	*x = FreeSlotsRequest{}
	mi := &file_booking_v1_booking_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FreeSlotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FreeSlotsRequest) ProtoMessage() {}

func (x *FreeSlotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_booking_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FreeSlotsRequest.ProtoReflect.Descriptor instead.
func (*FreeSlotsRequest) Descriptor() ([]byte, []int) {
	return file_booking_v1_booking_proto_rawDescGZIP(), []int{8}
}

func (x *FreeSlotsRequest) GetBarberId() string {
	if x != nil {
		return x.BarberId
	}
	return ""
}

func (x *FreeSlotsRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *FreeSlotsRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

type FreeSlotsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BarberId      string                 `protobuf:"bytes,1,opt,name=barber_id,json=barberId,proto3" json:"barber_id,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Slots         []*Slot                `protobuf:"bytes,3,rep,name=slots,proto3" json:"slots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FreeSlotsResponse) Reset() {
	*x = FreeSlotsResponse{}
	mi := &file_booking_v1_booking_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FreeSlotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FreeSlotsResponse) ProtoMessage() {}

func (x *FreeSlotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_booking_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FreeSlotsResponse.ProtoReflect.Descriptor instead.
func (*FreeSlotsResponse) Descriptor() ([]byte, []int) {
	return file_booking_v1_booking_proto_rawDescGZIP(), []int{9}
}

func (x *FreeSlotsResponse) GetBarberId() string {
	if x != nil {
		return x.BarberId
	}
	return ""
}

func (x *FreeSlotsResponse) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *FreeSlotsResponse) GetSlots() []*Slot {
	if x != nil {
		return x.Slots
	}
	return nil
}

type SlotBooking struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	ClientName    string                 `protobuf:"bytes,2,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	ClientPhone   string                 `protobuf:"bytes,3,opt,name=client_phone,json=clientPhone,proto3" json:"client_phone,omitempty"`
	ServiceName   string                 `protobuf:"bytes,4,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlotBooking) Reset() {
	*x = SlotBooking{}
	mi := &file_booking_v1_booking_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlotBooking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotBooking) ProtoMessage() {}

func (x *SlotBooking) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_booking_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotBooking.ProtoReflect.Descriptor instead.
func (*SlotBooking) Descriptor() ([]byte, []int) {
	return file_booking_v1_booking_proto_rawDescGZIP(), []int{10}
}

func (x *SlotBooking) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *SlotBooking) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *SlotBooking) GetClientPhone() string {
	if x != nil {
		return x.ClientPhone
	}
	return ""
}

func (x *SlotBooking) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type Slot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        SlotStatus             `protobuf:"varint,1,opt,name=status,proto3,enum=booking.v1.SlotStatus" json:"status,omitempty"`
	TimeStart     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=time_start,json=timeStart,proto3" json:"time_start,omitempty"`
	TimeEnd       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=time_end,json=timeEnd,proto3" json:"time_end,omitempty"`
	Booking       *SlotBooking           `protobuf:"bytes,4,opt,name=booking,proto3" json:"booking,omitempty"` // заполнено только если status = BOOKED
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Slot) Reset() {
	*x = Slot{}
	mi := &file_booking_v1_booking_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Slot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slot) ProtoMessage() {}

func (x *Slot) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_booking_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Slot.ProtoReflect.Descriptor instead.
func (*Slot) Descriptor() ([]byte, []int) {
	return file_booking_v1_booking_proto_rawDescGZIP(), []int{11}
}

func (x *Slot) GetStatus() SlotStatus {
	if x != nil {
		return x.Status
	}
	return SlotStatus_SLOT_STATUS_UNSPECIFIED
}

func (x *Slot) GetTimeStart() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeStart
	}
	return nil
}

func (x *Slot) GetTimeEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeEnd
	}
	return nil
}

func (x *Slot) GetBooking() *SlotBooking {
	if x != nil {
		return x.Booking
	}
	return nil
}

type BookingEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	BarberId      string                 `protobuf:"bytes,2,opt,name=barber_id,json=barberId,proto3" json:"barber_id,omitempty"`
	ClientPhone   string                 `protobuf:"bytes,3,opt,name=client_phone,json=clientPhone,proto3" json:"client_phone,omitempty"`
	ClientName    string                 `protobuf:"bytes,4,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	ServiceId     string                 `protobuf:"bytes,5,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	ServiceName   string                 `protobuf:"bytes,6,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Price         int32                  `protobuf:"varint,7,opt,name=price,proto3" json:"price,omitempty"` // цена на момент записи (руб.)
	TimeStart     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=time_start,json=timeStart,proto3" json:"time_start,omitempty"`
	TimeEnd       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=time_end,json=timeEnd,proto3" json:"time_end,omitempty"`
	Status        BookingStatus          `protobuf:"varint,10,opt,name=status,proto3,enum=booking.v1.BookingStatus" json:"status,omitempty"`
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingEvent) Reset() {
	*x = BookingEvent{}
	mi := &file_booking_v1_booking_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingEvent) ProtoMessage() {}

func (x *BookingEvent) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_booking_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingEvent.ProtoReflect.Descriptor instead.
func (*BookingEvent) Descriptor() ([]byte, []int) {
	return file_booking_v1_booking_proto_rawDescGZIP(), []int{12}
}

func (x *BookingEvent) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *BookingEvent) GetBarberId() string {
	if x != nil {
		return x.BarberId
	}
	return ""
}

func (x *BookingEvent) GetClientPhone() string {
	if x != nil {
		return x.ClientPhone
	}
	return ""
}

func (x *BookingEvent) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *BookingEvent) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *BookingEvent) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *BookingEvent) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *BookingEvent) GetTimeStart() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeStart
	}
	return nil
}

func (x *BookingEvent) GetTimeEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeEnd
	}
	return nil
}

func (x *BookingEvent) GetStatus() BookingStatus {
	if x != nil {
		return x.Status
	}
	return BookingStatus_BOOKING_STATUS_UNSPECIFIED
}

func (x *BookingEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

var File_booking_v1_booking_proto protoreflect.FileDescriptor

const file_booking_v1_booking_proto_rawDesc = "" +
	"\n" +
	"\x18booking/v1/booking.proto\x12\n" +
	"booking.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd1\x01\n" +
	"\x14CreateBookingRequest\x12\x1b\n" +
	"\tbarber_id\x18\x01 \x01(\tR\bbarberId\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\tR\tserviceId\x12\x1f\n" +
	"\vclient_name\x18\x03 \x01(\tR\n" +
	"clientName\x12!\n" +
	"\fclient_phone\x18\x04 \x01(\tR\vclientPhone\x129\n" +
	"\n" +
	"time_start\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimeStart\"\xac\x01\n" +
	"\x14UpdateBookingRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x12\x1b\n" +
	"\tbarber_id\x18\x02 \x01(\tR\bbarberId\x12\x1d\n" +
	"\n" +
	"service_id\x18\x03 \x01(\tR\tserviceId\x129\n" +
	"\n" +
	"time_start\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimeStart\"\x8b\x01\n" +
	"\x1aUpdateBookingStatusRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x12\x1b\n" +
	"\tbarber_id\x18\x02 \x01(\tR\bbarberId\x121\n" +
	"\x06status\x18\x03 \x01(\x0e2\x19.booking.v1.BookingStatusR\x06status\"1\n" +
	"\x10BookingIdRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\"\xf0\x02\n" +
	"\aBooking\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x12\x1b\n" +
	"\tbarber_id\x18\x02 \x01(\tR\bbarberId\x12\x1d\n" +
	"\n" +
	"service_id\x18\x03 \x01(\tR\tserviceId\x12!\n" +
	"\fservice_name\x18\x04 \x01(\tR\vserviceName\x12\x1f\n" +
	"\vclient_name\x18\x05 \x01(\tR\n" +
	"clientName\x12!\n" +
	"\fclient_phone\x18\x06 \x01(\tR\vclientPhone\x129\n" +
	"\n" +
	"time_start\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimeStart\x125\n" +
	"\btime_end\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\atimeEnd\x121\n" +
	"\x06status\x18\t \x01(\x0e2\x19.booking.v1.BookingStatusR\x06status\"@\n" +
	"\x0fBookingResponse\x12-\n" +
	"\abooking\x18\x01 \x01(\v2\x13.booking.v1.BookingR\abooking\"?\n" +
	"\fSlotsRequest\x12\x1b\n" +
	"\tbarber_id\x18\x01 \x01(\tR\bbarberId\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\"h\n" +
	"\rSlotsResponse\x12\x1b\n" +
	"\tbarber_id\x18\x01 \x01(\tR\bbarberId\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12&\n" +
	"\x05slots\x18\x03 \x03(\v2\x10.booking.v1.SlotR\x05slots\"b\n" +
	"\x10FreeSlotsRequest\x12\x1b\n" +
	"\tbarber_id\x18\x01 \x01(\tR\bbarberId\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x1d\n" +
	"\n" +
	"service_id\x18\x03 \x01(\tR\tserviceId\"l\n" +
	"\x11FreeSlotsResponse\x12\x1b\n" +
	"\tbarber_id\x18\x01 \x01(\tR\bbarberId\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12&\n" +
	"\x05slots\x18\x03 \x03(\v2\x10.booking.v1.SlotR\x05slots\"\x93\x01\n" +
	"\vSlotBooking\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x12\x1f\n" +
	"\vclient_name\x18\x02 \x01(\tR\n" +
	"clientName\x12!\n" +
	"\fclient_phone\x18\x03 \x01(\tR\vclientPhone\x12!\n" +
	"\fservice_name\x18\x04 \x01(\tR\vserviceName\"\xdb\x01\n" +
	"\x04Slot\x12.\n" +
	"\x06status\x18\x01 \x01(\x0e2\x16.booking.v1.SlotStatusR\x06status\x129\n" +
	"\n" +
	"time_start\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimeStart\x125\n" +
	"\btime_end\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\atimeEnd\x121\n" +
	"\abooking\x18\x04 \x01(\v2\x17.booking.v1.SlotBookingR\abooking\"\xc8\x03\n" +
	"\fBookingEvent\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x12\x1b\n" +
	"\tbarber_id\x18\x02 \x01(\tR\bbarberId\x12!\n" +
	"\fclient_phone\x18\x03 \x01(\tR\vclientPhone\x12\x1f\n" +
	"\vclient_name\x18\x04 \x01(\tR\n" +
	"clientName\x12\x1d\n" +
	"\n" +
	"service_id\x18\x05 \x01(\tR\tserviceId\x12!\n" +
	"\fservice_name\x18\x06 \x01(\tR\vserviceName\x12\x14\n" +
	"\x05price\x18\a \x01(\x05R\x05price\x129\n" +
	"\n" +
	"time_start\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\ttimeStart\x125\n" +
	"\btime_end\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\atimeEnd\x121\n" +
	"\x06status\x18\n" +
	" \x01(\x0e2\x19.booking.v1.BookingStatusR\x06status\x12;\n" +
	"\voccurred_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt*p\n" +
	"\n" +
	"SlotStatus\x12\x1b\n" +
	"\x17SLOT_STATUS_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10SLOT_STATUS_FREE\x10\x01\x12\x16\n" +
	"\x12SLOT_STATUS_BOOKED\x10\x02\x12\x17\n" +
	"\x13SLOT_STATUS_BLOCKED\x10\x03*\xa3\x01\n" +
	"\rBookingStatus\x12\x1e\n" +
	"\x1aBOOKING_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16BOOKING_STATUS_PENDING\x10\x01\x12\x1c\n" +
	"\x18BOOKING_STATUS_COMPLETED\x10\x02\x12\x1c\n" +
	"\x18BOOKING_STATUS_CANCELLED\x10\x03\x12\x1a\n" +
	"\x16BOOKING_STATUS_NO_SHOW\x10\x042\xaa\x04\n" +
	"\x0eBookingService\x12N\n" +
	"\rCreateBooking\x12 .booking.v1.CreateBookingRequest\x1a\x1b.booking.v1.BookingResponse\x12G\n" +
	"\n" +
	"GetBooking\x12\x1c.booking.v1.BookingIdRequest\x1a\x1b.booking.v1.BookingResponse\x12N\n" +
	"\rUpdateBooking\x12 .booking.v1.UpdateBookingRequest\x1a\x1b.booking.v1.BookingResponse\x12Z\n" +
	"\x13UpdateBookingStatus\x12&.booking.v1.UpdateBookingStatusRequest\x1a\x1b.booking.v1.BookingResponse\x12E\n" +
	"\rDeleteBooking\x12\x1c.booking.v1.BookingIdRequest\x1a\x16.google.protobuf.Empty\x12?\n" +
	"\bGetSlots\x12\x18.booking.v1.SlotsRequest\x1a\x19.booking.v1.SlotsResponse\x12K\n" +
	"\fGetFreeSlots\x12\x1c.booking.v1.FreeSlotsRequest\x1a\x1d.booking.v1.FreeSlotsResponseBFZDgithub.com/RomanKovalev007/barber_crm/api/proto/booking/v1;bookingv1b\x06proto3"

var (
	file_booking_v1_booking_proto_rawDescOnce sync.Once
	file_booking_v1_booking_proto_rawDescData []byte
)

func file_booking_v1_booking_proto_rawDescGZIP() []byte {
	file_booking_v1_booking_proto_rawDescOnce.Do(func() {
		file_booking_v1_booking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_booking_v1_booking_proto_rawDesc), len(file_booking_v1_booking_proto_rawDesc)))
	})
	return file_booking_v1_booking_proto_rawDescData
}

var file_booking_v1_booking_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_booking_v1_booking_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_booking_v1_booking_proto_goTypes = []any{
	(SlotStatus)(0),                    // 0: booking.v1.SlotStatus
	(BookingStatus)(0),                 // 1: booking.v1.BookingStatus
	(*CreateBookingRequest)(nil),       // 2: booking.v1.CreateBookingRequest
	(*UpdateBookingRequest)(nil),       // 3: booking.v1.UpdateBookingRequest
	(*UpdateBookingStatusRequest)(nil), // 4: booking.v1.UpdateBookingStatusRequest
	(*BookingIdRequest)(nil),           // 5: booking.v1.BookingIdRequest
	(*Booking)(nil),                    // 6: booking.v1.Booking
	(*BookingResponse)(nil),            // 7: booking.v1.BookingResponse
	(*SlotsRequest)(nil),               // 8: booking.v1.SlotsRequest
	(*SlotsResponse)(nil),              // 9: booking.v1.SlotsResponse
	(*FreeSlotsRequest)(nil),           // 10: booking.v1.FreeSlotsRequest
	(*FreeSlotsResponse)(nil),          // 11: booking.v1.FreeSlotsResponse
	(*SlotBooking)(nil),                // 12: booking.v1.SlotBooking
	(*Slot)(nil),                       // 13: booking.v1.Slot
	(*BookingEvent)(nil),               // 14: booking.v1.BookingEvent
	(*timestamppb.Timestamp)(nil),      // 15: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),              // 16: google.protobuf.Empty
}
var file_booking_v1_booking_proto_depIdxs = []int32{
	15, // 0: booking.v1.CreateBookingRequest.time_start:type_name -> google.protobuf.Timestamp
	15, // 1: booking.v1.UpdateBookingRequest.time_start:type_name -> google.protobuf.Timestamp
	1,  // 2: booking.v1.UpdateBookingStatusRequest.status:type_name -> booking.v1.BookingStatus
	15, // 3: booking.v1.Booking.time_start:type_name -> google.protobuf.Timestamp
	15, // 4: booking.v1.Booking.time_end:type_name -> google.protobuf.Timestamp
	1,  // 5: booking.v1.Booking.status:type_name -> booking.v1.BookingStatus
	6,  // 6: booking.v1.BookingResponse.booking:type_name -> booking.v1.Booking
	13, // 7: booking.v1.SlotsResponse.slots:type_name -> booking.v1.Slot
	13, // 8: booking.v1.FreeSlotsResponse.slots:type_name -> booking.v1.Slot
	0,  // 9: booking.v1.Slot.status:type_name -> booking.v1.SlotStatus
	15, // 10: booking.v1.Slot.time_start:type_name -> google.protobuf.Timestamp
	15, // 11: booking.v1.Slot.time_end:type_name -> google.protobuf.Timestamp
	12, // 12: booking.v1.Slot.booking:type_name -> booking.v1.SlotBooking
	15, // 13: booking.v1.BookingEvent.time_start:type_name -> google.protobuf.Timestamp
	15, // 14: booking.v1.BookingEvent.time_end:type_name -> google.protobuf.Timestamp
	1,  // 15: booking.v1.BookingEvent.status:type_name -> booking.v1.BookingStatus
	15, // 16: booking.v1.BookingEvent.occurred_at:type_name -> google.protobuf.Timestamp
	2,  // 17: booking.v1.BookingService.CreateBooking:input_type -> booking.v1.CreateBookingRequest
	5,  // 18: booking.v1.BookingService.GetBooking:input_type -> booking.v1.BookingIdRequest
	3,  // 19: booking.v1.BookingService.UpdateBooking:input_type -> booking.v1.UpdateBookingRequest
	4,  // 20: booking.v1.BookingService.UpdateBookingStatus:input_type -> booking.v1.UpdateBookingStatusRequest
	5,  // 21: booking.v1.BookingService.DeleteBooking:input_type -> booking.v1.BookingIdRequest
	8,  // 22: booking.v1.BookingService.GetSlots:input_type -> booking.v1.SlotsRequest
	10, // 23: booking.v1.BookingService.GetFreeSlots:input_type -> booking.v1.FreeSlotsRequest
	7,  // 24: booking.v1.BookingService.CreateBooking:output_type -> booking.v1.BookingResponse
	7,  // 25: booking.v1.BookingService.GetBooking:output_type -> booking.v1.BookingResponse
	7,  // 26: booking.v1.BookingService.UpdateBooking:output_type -> booking.v1.BookingResponse
	7,  // 27: booking.v1.BookingService.UpdateBookingStatus:output_type -> booking.v1.BookingResponse
	16, // 28: booking.v1.BookingService.DeleteBooking:output_type -> google.protobuf.Empty
	9,  // 29: booking.v1.BookingService.GetSlots:output_type -> booking.v1.SlotsResponse
	11, // 30: booking.v1.BookingService.GetFreeSlots:output_type -> booking.v1.FreeSlotsResponse
	24, // [24:31] is the sub-list for method output_type
	17, // [17:24] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_booking_v1_booking_proto_init() }
func file_booking_v1_booking_proto_init() {
	if File_booking_v1_booking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_booking_v1_booking_proto_rawDesc), len(file_booking_v1_booking_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_booking_v1_booking_proto_goTypes,
		DependencyIndexes: file_booking_v1_booking_proto_depIdxs,
		EnumInfos:         file_booking_v1_booking_proto_enumTypes,
		MessageInfos:      file_booking_v1_booking_proto_msgTypes,
	}.Build()
	File_booking_v1_booking_proto = out.File
	file_booking_v1_booking_proto_goTypes = nil
	file_booking_v1_booking_proto_depIdxs = nil
}
