// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: booking/v1/booking.proto

package bookingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SlotStatus int32

const (
	SlotStatus_SLOT_UNKNOWN SlotStatus = 0
	SlotStatus_SLOT_FREE    SlotStatus = 1
	SlotStatus_SLOT_BOOKED  SlotStatus = 2
	SlotStatus_SLOT_BLOCKED SlotStatus = 3
)

// Enum value maps for SlotStatus.
var (
	SlotStatus_name = map[int32]string{
		0: "SLOT_UNKNOWN",
		1: "SLOT_FREE",
		2: "SLOT_BOOKED",
		3: "SLOT_BLOCKED",
	}
	SlotStatus_value = map[string]int32{
		"SLOT_UNKNOWN": 0,
		"SLOT_FREE":    1,
		"SLOT_BOOKED":  2,
		"SLOT_BLOCKED": 3,
	}
)

func (x SlotStatus) Enum() *SlotStatus {
	p := new(SlotStatus)
	*p = x
	return p
}

func (x SlotStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SlotStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_booking_v1_booking_proto_enumTypes[0].Descriptor()
}

func (SlotStatus) Type() protoreflect.EnumType {
	return &file_booking_v1_booking_proto_enumTypes[0]
}

func (x SlotStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SlotStatus.Descriptor instead.
func (SlotStatus) EnumDescriptor() ([]byte, []int) {
	return file_booking_v1_booking_proto_rawDescGZIP(), []int{0}
}

type BookingStatus int32

const (
	BookingStatus_BOOKING_STATUS_UNSPECIFIED BookingStatus = 0
	BookingStatus_BOOKING_STATUS_PENDING     BookingStatus = 1
	BookingStatus_BOOKING_STATUS_COMPLETED   BookingStatus = 2
	BookingStatus_BOOKING_STATUS_CANCELLED   BookingStatus = 3
	BookingStatus_BOOKING_STATUS_NO_SHOW     BookingStatus = 4
)

// Enum value maps for BookingStatus.
var (
	BookingStatus_name = map[int32]string{
		0: "BOOKING_STATUS_UNSPECIFIED",
		1: "BOOKING_STATUS_PENDING",
		2: "BOOKING_STATUS_COMPLETED",
		3: "BOOKING_STATUS_CANCELLED",
		4: "BOOKING_STATUS_NO_SHOW",
	}
	BookingStatus_value = map[string]int32{
		"BOOKING_STATUS_UNSPECIFIED": 0,
		"BOOKING_STATUS_PENDING":     1,
		"BOOKING_STATUS_COMPLETED":   2,
		"BOOKING_STATUS_CANCELLED":   3,
		"BOOKING_STATUS_NO_SHOW":     4,
	}
)

func (x BookingStatus) Enum() *BookingStatus {
	p := new(BookingStatus)
	*p = x
	return p
}

func (x BookingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BookingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_booking_v1_booking_proto_enumTypes[1].Descriptor()
}

func (BookingStatus) Type() protoreflect.EnumType {
	return &file_booking_v1_booking_proto_enumTypes[1]
}

func (x BookingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BookingStatus.Descriptor instead.
func (BookingStatus) EnumDescriptor() ([]byte, []int) {
	return file_booking_v1_booking_proto_rawDescGZIP(), []int{1}
}

type CreateBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientName    string                 `protobuf:"bytes,1,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	BarberId      string                 `protobuf:"bytes,2,opt,name=barber_id,json=barberId,proto3" json:"barber_id,omitempty"`
	ServId        string                 `protobuf:"bytes,3,opt,name=serv_id,json=servId,proto3" json:"serv_id,omitempty"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	TimeStart     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=time_start,json=timeStart,proto3" json:"time_start,omitempty"`
	TimeEnd       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=time_end,json=timeEnd,proto3" json:"time_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookingRequest) Reset() {
	*x = CreateBookingRequest{}
	mi := &file_booking_v1_booking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookingRequest) ProtoMessage() {}

func (x *CreateBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_booking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookingRequest.ProtoReflect.Descriptor instead.
func (*CreateBookingRequest) Descriptor() ([]byte, []int) {
	return file_booking_v1_booking_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBookingRequest) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *CreateBookingRequest) GetBarberId() string {
	if x != nil {
		return x.BarberId
	}
	return ""
}

func (x *CreateBookingRequest) GetServId() string {
	if x != nil {
		return x.ServId
	}
	return ""
}

func (x *CreateBookingRequest) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *CreateBookingRequest) GetTimeStart() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeStart
	}
	return nil
}

func (x *CreateBookingRequest) GetTimeEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeEnd
	}
	return nil
}

type Booking struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	ClientName    string                 `protobuf:"bytes,2,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	BarberId      string                 `protobuf:"bytes,3,opt,name=barber_id,json=barberId,proto3" json:"barber_id,omitempty"`
	ServId        string                 `protobuf:"bytes,4,opt,name=serv_id,json=servId,proto3" json:"serv_id,omitempty"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=date,proto3" json:"date,omitempty"`
	TimeStart     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=time_start,json=timeStart,proto3" json:"time_start,omitempty"`
	TimeEnd       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=time_end,json=timeEnd,proto3" json:"time_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Booking) Reset() {
	*x = Booking{}
	mi := &file_booking_v1_booking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Booking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Booking) ProtoMessage() {}

func (x *Booking) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_booking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Booking.ProtoReflect.Descriptor instead.
func (*Booking) Descriptor() ([]byte, []int) {
	return file_booking_v1_booking_proto_rawDescGZIP(), []int{1}
}

func (x *Booking) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *Booking) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *Booking) GetBarberId() string {
	if x != nil {
		return x.BarberId
	}
	return ""
}

func (x *Booking) GetServId() string {
	if x != nil {
		return x.ServId
	}
	return ""
}

func (x *Booking) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *Booking) GetTimeStart() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeStart
	}
	return nil
}

func (x *Booking) GetTimeEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeEnd
	}
	return nil
}

type BookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Booking       *Booking               `protobuf:"bytes,1,opt,name=booking,proto3" json:"booking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingResponse) Reset() {
	*x = BookingResponse{}
	mi := &file_booking_v1_booking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingResponse) ProtoMessage() {}

func (x *BookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_booking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingResponse.ProtoReflect.Descriptor instead.
func (*BookingResponse) Descriptor() ([]byte, []int) {
	return file_booking_v1_booking_proto_rawDescGZIP(), []int{2}
}

func (x *BookingResponse) GetBooking() *Booking {
	if x != nil {
		return x.Booking
	}
	return nil
}

type BookingIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingIdRequest) Reset() {
	*x = BookingIdRequest{}
	mi := &file_booking_v1_booking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingIdRequest) ProtoMessage() {}

func (x *BookingIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_booking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingIdRequest.ProtoReflect.Descriptor instead.
func (*BookingIdRequest) Descriptor() ([]byte, []int) {
	return file_booking_v1_booking_proto_rawDescGZIP(), []int{3}
}

func (x *BookingIdRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	ClientName    string                 `protobuf:"bytes,2,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_booking_v1_booking_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_booking_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_booking_v1_booking_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteResponse) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *DeleteResponse) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

type SlotsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BarberId      string                 `protobuf:"bytes,1,opt,name=barber_id,json=barberId,proto3" json:"barber_id,omitempty"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlotsRequest) Reset() {
	*x = SlotsRequest{}
	mi := &file_booking_v1_booking_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotsRequest) ProtoMessage() {}

func (x *SlotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_booking_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotsRequest.ProtoReflect.Descriptor instead.
func (*SlotsRequest) Descriptor() ([]byte, []int) {
	return file_booking_v1_booking_proto_rawDescGZIP(), []int{5}
}

func (x *SlotsRequest) GetBarberId() string {
	if x != nil {
		return x.BarberId
	}
	return ""
}

func (x *SlotsRequest) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

type Slot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        SlotStatus             `protobuf:"varint,1,opt,name=status,proto3,enum=booking.v1.SlotStatus" json:"status,omitempty"`
	TimeStart     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=time_start,json=timeStart,proto3" json:"time_start,omitempty"`
	TimeEnd       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=time_end,json=timeEnd,proto3" json:"time_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Slot) Reset() {
	*x = Slot{}
	mi := &file_booking_v1_booking_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Slot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slot) ProtoMessage() {}

func (x *Slot) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_booking_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Slot.ProtoReflect.Descriptor instead.
func (*Slot) Descriptor() ([]byte, []int) {
	return file_booking_v1_booking_proto_rawDescGZIP(), []int{6}
}

func (x *Slot) GetStatus() SlotStatus {
	if x != nil {
		return x.Status
	}
	return SlotStatus_SLOT_UNKNOWN
}

func (x *Slot) GetTimeStart() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeStart
	}
	return nil
}

func (x *Slot) GetTimeEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeEnd
	}
	return nil
}

type SlotsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BarberId      string                 `protobuf:"bytes,1,opt,name=barber_id,json=barberId,proto3" json:"barber_id,omitempty"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Slots         []*Slot                `protobuf:"bytes,3,rep,name=slots,proto3" json:"slots,omitempty"`
	Priority      int32                  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlotsResponse) Reset() {
	*x = SlotsResponse{}
	mi := &file_booking_v1_booking_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotsResponse) ProtoMessage() {}

func (x *SlotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_booking_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotsResponse.ProtoReflect.Descriptor instead.
func (*SlotsResponse) Descriptor() ([]byte, []int) {
	return file_booking_v1_booking_proto_rawDescGZIP(), []int{7}
}

func (x *SlotsResponse) GetBarberId() string {
	if x != nil {
		return x.BarberId
	}
	return ""
}

func (x *SlotsResponse) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *SlotsResponse) GetSlots() []*Slot {
	if x != nil {
		return x.Slots
	}
	return nil
}

func (x *SlotsResponse) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type BookingEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	BarberId      string                 `protobuf:"bytes,2,opt,name=barber_id,json=barberId,proto3" json:"barber_id,omitempty"`
	ClientPhone   string                 `protobuf:"bytes,3,opt,name=client_phone,json=clientPhone,proto3" json:"client_phone,omitempty"`
	ClientName    string                 `protobuf:"bytes,4,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	ServiceId     string                 `protobuf:"bytes,5,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	ServiceName   string                 `protobuf:"bytes,6,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Price         int32                  `protobuf:"varint,7,opt,name=price,proto3" json:"price,omitempty"` // цена на момент записи (руб.)
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Status        BookingStatus          `protobuf:"varint,10,opt,name=status,proto3,enum=booking.v1.BookingStatus" json:"status,omitempty"`
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingEvent) Reset() {
	*x = BookingEvent{}
	mi := &file_booking_v1_booking_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingEvent) ProtoMessage() {}

func (x *BookingEvent) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_booking_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingEvent.ProtoReflect.Descriptor instead.
func (*BookingEvent) Descriptor() ([]byte, []int) {
	return file_booking_v1_booking_proto_rawDescGZIP(), []int{8}
}

func (x *BookingEvent) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *BookingEvent) GetBarberId() string {
	if x != nil {
		return x.BarberId
	}
	return ""
}

func (x *BookingEvent) GetClientPhone() string {
	if x != nil {
		return x.ClientPhone
	}
	return ""
}

func (x *BookingEvent) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *BookingEvent) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *BookingEvent) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *BookingEvent) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *BookingEvent) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *BookingEvent) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *BookingEvent) GetStatus() BookingStatus {
	if x != nil {
		return x.Status
	}
	return BookingStatus_BOOKING_STATUS_UNSPECIFIED
}

func (x *BookingEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

var File_booking_v1_booking_proto protoreflect.FileDescriptor

const file_booking_v1_booking_proto_rawDesc = "" +
	"\n" +
	"\x18booking/v1/booking.proto\x12\n" +
	"booking.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8f\x02\n" +
	"\x14CreateBookingRequest\x12\x1f\n" +
	"\vclient_name\x18\x01 \x01(\tR\n" +
	"clientName\x12\x1b\n" +
	"\tbarber_id\x18\x02 \x01(\tR\bbarberId\x12\x17\n" +
	"\aserv_id\x18\x03 \x01(\tR\x06servId\x12.\n" +
	"\x04date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x129\n" +
	"\n" +
	"time_start\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimeStart\x125\n" +
	"\btime_end\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\atimeEnd\"\xa1\x02\n" +
	"\aBooking\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x12\x1f\n" +
	"\vclient_name\x18\x02 \x01(\tR\n" +
	"clientName\x12\x1b\n" +
	"\tbarber_id\x18\x03 \x01(\tR\bbarberId\x12\x17\n" +
	"\aserv_id\x18\x04 \x01(\tR\x06servId\x12.\n" +
	"\x04date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x129\n" +
	"\n" +
	"time_start\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimeStart\x125\n" +
	"\btime_end\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\atimeEnd\"@\n" +
	"\x0fBookingResponse\x12-\n" +
	"\abooking\x18\x01 \x01(\v2\x13.booking.v1.BookingR\abooking\"1\n" +
	"\x10BookingIdRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\"P\n" +
	"\x0eDeleteResponse\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x12\x1f\n" +
	"\vclient_name\x18\x02 \x01(\tR\n" +
	"clientName\"[\n" +
	"\fSlotsRequest\x12\x1b\n" +
	"\tbarber_id\x18\x01 \x01(\tR\bbarberId\x12.\n" +
	"\x04date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\"\xa8\x01\n" +
	"\x04Slot\x12.\n" +
	"\x06status\x18\x01 \x01(\x0e2\x16.booking.v1.SlotStatusR\x06status\x129\n" +
	"\n" +
	"time_start\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimeStart\x125\n" +
	"\btime_end\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\atimeEnd\"\xa0\x01\n" +
	"\rSlotsResponse\x12\x1b\n" +
	"\tbarber_id\x18\x01 \x01(\tR\bbarberId\x12.\n" +
	"\x04date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12&\n" +
	"\x05slots\x18\x03 \x03(\v2\x10.booking.v1.SlotR\x05slots\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x05R\bpriority\"\xc8\x03\n" +
	"\fBookingEvent\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x12\x1b\n" +
	"\tbarber_id\x18\x02 \x01(\tR\bbarberId\x12!\n" +
	"\fclient_phone\x18\x03 \x01(\tR\vclientPhone\x12\x1f\n" +
	"\vclient_name\x18\x04 \x01(\tR\n" +
	"clientName\x12\x1d\n" +
	"\n" +
	"service_id\x18\x05 \x01(\tR\tserviceId\x12!\n" +
	"\fservice_name\x18\x06 \x01(\tR\vserviceName\x12\x14\n" +
	"\x05price\x18\a \x01(\x05R\x05price\x129\n" +
	"\n" +
	"start_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x121\n" +
	"\x06status\x18\n" +
	" \x01(\x0e2\x19.booking.v1.BookingStatusR\x06status\x12;\n" +
	"\voccurred_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt*P\n" +
	"\n" +
	"SlotStatus\x12\x10\n" +
	"\fSLOT_UNKNOWN\x10\x00\x12\r\n" +
	"\tSLOT_FREE\x10\x01\x12\x0f\n" +
	"\vSLOT_BOOKED\x10\x02\x12\x10\n" +
	"\fSLOT_BLOCKED\x10\x03*\xa3\x01\n" +
	"\rBookingStatus\x12\x1e\n" +
	"\x1aBOOKING_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16BOOKING_STATUS_PENDING\x10\x01\x12\x1c\n" +
	"\x18BOOKING_STATUS_COMPLETED\x10\x02\x12\x1c\n" +
	"\x18BOOKING_STATUS_CANCELLED\x10\x03\x12\x1a\n" +
	"\x16BOOKING_STATUS_NO_SHOW\x10\x042\xba\x03\n" +
	"\x0eBookingService\x12N\n" +
	"\rCreateBooking\x12 .booking.v1.CreateBookingRequest\x1a\x1b.booking.v1.BookingResponse\x12G\n" +
	"\n" +
	"GetBooking\x12\x1c.booking.v1.BookingIdRequest\x1a\x1b.booking.v1.BookingResponse\x12A\n" +
	"\rUpdateBooking\x12\x13.booking.v1.Booking\x1a\x1b.booking.v1.BookingResponse\x12I\n" +
	"\rDeleteBooking\x12\x1c.booking.v1.BookingIdRequest\x1a\x1a.booking.v1.DeleteResponse\x12A\n" +
	"\n" +
	"GetWorkDay\x12\x18.booking.v1.SlotsRequest\x1a\x19.booking.v1.SlotsResponse\x12>\n" +
	"\aGetFree\x12\x18.booking.v1.SlotsRequest\x1a\x19.booking.v1.SlotsResponseBFZDgithub.com/RomanKovalev007/barber_crm/api/proto/booking/v1;bookingv1b\x06proto3"

var (
	file_booking_v1_booking_proto_rawDescOnce sync.Once
	file_booking_v1_booking_proto_rawDescData []byte
)

func file_booking_v1_booking_proto_rawDescGZIP() []byte {
	file_booking_v1_booking_proto_rawDescOnce.Do(func() {
		file_booking_v1_booking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_booking_v1_booking_proto_rawDesc), len(file_booking_v1_booking_proto_rawDesc)))
	})
	return file_booking_v1_booking_proto_rawDescData
}

var file_booking_v1_booking_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_booking_v1_booking_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_booking_v1_booking_proto_goTypes = []any{
	(SlotStatus)(0),               // 0: booking.v1.SlotStatus
	(BookingStatus)(0),            // 1: booking.v1.BookingStatus
	(*CreateBookingRequest)(nil),  // 2: booking.v1.CreateBookingRequest
	(*Booking)(nil),               // 3: booking.v1.Booking
	(*BookingResponse)(nil),       // 4: booking.v1.BookingResponse
	(*BookingIdRequest)(nil),      // 5: booking.v1.BookingIdRequest
	(*DeleteResponse)(nil),        // 6: booking.v1.DeleteResponse
	(*SlotsRequest)(nil),          // 7: booking.v1.SlotsRequest
	(*Slot)(nil),                  // 8: booking.v1.Slot
	(*SlotsResponse)(nil),         // 9: booking.v1.SlotsResponse
	(*BookingEvent)(nil),          // 10: booking.v1.BookingEvent
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_booking_v1_booking_proto_depIdxs = []int32{
	11, // 0: booking.v1.CreateBookingRequest.date:type_name -> google.protobuf.Timestamp
	11, // 1: booking.v1.CreateBookingRequest.time_start:type_name -> google.protobuf.Timestamp
	11, // 2: booking.v1.CreateBookingRequest.time_end:type_name -> google.protobuf.Timestamp
	11, // 3: booking.v1.Booking.date:type_name -> google.protobuf.Timestamp
	11, // 4: booking.v1.Booking.time_start:type_name -> google.protobuf.Timestamp
	11, // 5: booking.v1.Booking.time_end:type_name -> google.protobuf.Timestamp
	3,  // 6: booking.v1.BookingResponse.booking:type_name -> booking.v1.Booking
	11, // 7: booking.v1.SlotsRequest.date:type_name -> google.protobuf.Timestamp
	0,  // 8: booking.v1.Slot.status:type_name -> booking.v1.SlotStatus
	11, // 9: booking.v1.Slot.time_start:type_name -> google.protobuf.Timestamp
	11, // 10: booking.v1.Slot.time_end:type_name -> google.protobuf.Timestamp
	11, // 11: booking.v1.SlotsResponse.date:type_name -> google.protobuf.Timestamp
	8,  // 12: booking.v1.SlotsResponse.slots:type_name -> booking.v1.Slot
	11, // 13: booking.v1.BookingEvent.start_time:type_name -> google.protobuf.Timestamp
	11, // 14: booking.v1.BookingEvent.end_time:type_name -> google.protobuf.Timestamp
	1,  // 15: booking.v1.BookingEvent.status:type_name -> booking.v1.BookingStatus
	11, // 16: booking.v1.BookingEvent.occurred_at:type_name -> google.protobuf.Timestamp
	2,  // 17: booking.v1.BookingService.CreateBooking:input_type -> booking.v1.CreateBookingRequest
	5,  // 18: booking.v1.BookingService.GetBooking:input_type -> booking.v1.BookingIdRequest
	3,  // 19: booking.v1.BookingService.UpdateBooking:input_type -> booking.v1.Booking
	5,  // 20: booking.v1.BookingService.DeleteBooking:input_type -> booking.v1.BookingIdRequest
	7,  // 21: booking.v1.BookingService.GetWorkDay:input_type -> booking.v1.SlotsRequest
	7,  // 22: booking.v1.BookingService.GetFree:input_type -> booking.v1.SlotsRequest
	4,  // 23: booking.v1.BookingService.CreateBooking:output_type -> booking.v1.BookingResponse
	4,  // 24: booking.v1.BookingService.GetBooking:output_type -> booking.v1.BookingResponse
	4,  // 25: booking.v1.BookingService.UpdateBooking:output_type -> booking.v1.BookingResponse
	6,  // 26: booking.v1.BookingService.DeleteBooking:output_type -> booking.v1.DeleteResponse
	9,  // 27: booking.v1.BookingService.GetWorkDay:output_type -> booking.v1.SlotsResponse
	9,  // 28: booking.v1.BookingService.GetFree:output_type -> booking.v1.SlotsResponse
	23, // [23:29] is the sub-list for method output_type
	17, // [17:23] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_booking_v1_booking_proto_init() }
func file_booking_v1_booking_proto_init() {
	if File_booking_v1_booking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_booking_v1_booking_proto_rawDesc), len(file_booking_v1_booking_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_booking_v1_booking_proto_goTypes,
		DependencyIndexes: file_booking_v1_booking_proto_depIdxs,
		EnumInfos:         file_booking_v1_booking_proto_enumTypes,
		MessageInfos:      file_booking_v1_booking_proto_msgTypes,
	}.Build()
	File_booking_v1_booking_proto = out.File
	file_booking_v1_booking_proto_goTypes = nil
	file_booking_v1_booking_proto_depIdxs = nil
}
