// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: staff/v1/staff.proto

package staffv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScheduleEventType int32

const (
	ScheduleEventType_SCHEDULE_EVENT_UNSPECIFIED ScheduleEventType = 0
	ScheduleEventType_SCHEDULE_EVENT_ADDED       ScheduleEventType = 1
	ScheduleEventType_SCHEDULE_EVENT_DELETED     ScheduleEventType = 2
)

// Enum value maps for ScheduleEventType.
var (
	ScheduleEventType_name = map[int32]string{
		0: "SCHEDULE_EVENT_UNSPECIFIED",
		1: "SCHEDULE_EVENT_ADDED",
		2: "SCHEDULE_EVENT_DELETED",
	}
	ScheduleEventType_value = map[string]int32{
		"SCHEDULE_EVENT_UNSPECIFIED": 0,
		"SCHEDULE_EVENT_ADDED":       1,
		"SCHEDULE_EVENT_DELETED":     2,
	}
)

func (x ScheduleEventType) Enum() *ScheduleEventType {
	p := new(ScheduleEventType)
	*p = x
	return p
}

func (x ScheduleEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScheduleEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_staff_v1_staff_proto_enumTypes[0].Descriptor()
}

func (ScheduleEventType) Type() protoreflect.EnumType {
	return &file_staff_v1_staff_proto_enumTypes[0]
}

func (x ScheduleEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScheduleEventType.Descriptor instead.
func (ScheduleEventType) EnumDescriptor() ([]byte, []int) {
	return file_staff_v1_staff_proto_rawDescGZIP(), []int{0}
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_staff_v1_staff_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staff_v1_staff_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_staff_v1_staff_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresIn     int32                  `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	Barber        *BarberResponse        `protobuf:"bytes,4,opt,name=barber,proto3" json:"barber,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_staff_v1_staff_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_staff_v1_staff_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_staff_v1_staff_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginResponse) GetExpiresIn() int32 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *LoginResponse) GetBarber() *BarberResponse {
	if x != nil {
		return x.Barber
	}
	return nil
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_staff_v1_staff_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staff_v1_staff_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_staff_v1_staff_proto_rawDescGZIP(), []int{2}
}

func (x *LogoutRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_staff_v1_staff_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staff_v1_staff_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_staff_v1_staff_proto_rawDescGZIP(), []int{3}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresIn     int32                  `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_staff_v1_staff_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_staff_v1_staff_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_staff_v1_staff_proto_rawDescGZIP(), []int{4}
}

func (x *RefreshTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshTokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshTokenResponse) GetExpiresIn() int32 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

type GetBarberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBarberRequest) Reset() {
	*x = GetBarberRequest{}
	mi := &file_staff_v1_staff_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBarberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBarberRequest) ProtoMessage() {}

func (x *GetBarberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staff_v1_staff_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBarberRequest.ProtoReflect.Descriptor instead.
func (*GetBarberRequest) Descriptor() ([]byte, []int) {
	return file_staff_v1_staff_proto_rawDescGZIP(), []int{5}
}

func (x *GetBarberRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BarberResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PhotoUrl       string                 `protobuf:"bytes,3,opt,name=photo_url,json=photoUrl,proto3" json:"photo_url,omitempty"`
	Specialization string                 `protobuf:"bytes,4,opt,name=specialization,proto3" json:"specialization,omitempty"`
	Rating         float64                `protobuf:"fixed64,5,opt,name=rating,proto3" json:"rating,omitempty"`
	Services       []*ServiceResponse     `protobuf:"bytes,6,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BarberResponse) Reset() {
	*x = BarberResponse{}
	mi := &file_staff_v1_staff_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BarberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BarberResponse) ProtoMessage() {}

func (x *BarberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_staff_v1_staff_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BarberResponse.ProtoReflect.Descriptor instead.
func (*BarberResponse) Descriptor() ([]byte, []int) {
	return file_staff_v1_staff_proto_rawDescGZIP(), []int{6}
}

func (x *BarberResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BarberResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BarberResponse) GetPhotoUrl() string {
	if x != nil {
		return x.PhotoUrl
	}
	return ""
}

func (x *BarberResponse) GetSpecialization() string {
	if x != nil {
		return x.Specialization
	}
	return ""
}

func (x *BarberResponse) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *BarberResponse) GetServices() []*ServiceResponse {
	if x != nil {
		return x.Services
	}
	return nil
}

type ListBarbersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBarbersRequest) Reset() {
	*x = ListBarbersRequest{}
	mi := &file_staff_v1_staff_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBarbersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBarbersRequest) ProtoMessage() {}

func (x *ListBarbersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staff_v1_staff_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBarbersRequest.ProtoReflect.Descriptor instead.
func (*ListBarbersRequest) Descriptor() ([]byte, []int) {
	return file_staff_v1_staff_proto_rawDescGZIP(), []int{7}
}

type ListBarbersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Barbers       []*BarberResponse      `protobuf:"bytes,1,rep,name=barbers,proto3" json:"barbers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBarbersResponse) Reset() {
	*x = ListBarbersResponse{}
	mi := &file_staff_v1_staff_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBarbersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBarbersResponse) ProtoMessage() {}

func (x *ListBarbersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_staff_v1_staff_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBarbersResponse.ProtoReflect.Descriptor instead.
func (*ListBarbersResponse) Descriptor() ([]byte, []int) {
	return file_staff_v1_staff_proto_rawDescGZIP(), []int{8}
}

func (x *ListBarbersResponse) GetBarbers() []*BarberResponse {
	if x != nil {
		return x.Barbers
	}
	return nil
}

type ScheduleDay struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BarberId      string                 `protobuf:"bytes,2,opt,name=barber_id,json=barberId,proto3" json:"barber_id,omitempty"`
	Date          string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	StartTime     string                 `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleDay) Reset() {
	*x = ScheduleDay{}
	mi := &file_staff_v1_staff_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleDay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleDay) ProtoMessage() {}

func (x *ScheduleDay) ProtoReflect() protoreflect.Message {
	mi := &file_staff_v1_staff_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleDay.ProtoReflect.Descriptor instead.
func (*ScheduleDay) Descriptor() ([]byte, []int) {
	return file_staff_v1_staff_proto_rawDescGZIP(), []int{9}
}

func (x *ScheduleDay) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ScheduleDay) GetBarberId() string {
	if x != nil {
		return x.BarberId
	}
	return ""
}

func (x *ScheduleDay) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *ScheduleDay) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *ScheduleDay) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

type AddScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BarberId      string                 `protobuf:"bytes,1,opt,name=barber_id,json=barberId,proto3" json:"barber_id,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	StartTime     string                 `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddScheduleRequest) Reset() {
	*x = AddScheduleRequest{}
	mi := &file_staff_v1_staff_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddScheduleRequest) ProtoMessage() {}

func (x *AddScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staff_v1_staff_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddScheduleRequest.ProtoReflect.Descriptor instead.
func (*AddScheduleRequest) Descriptor() ([]byte, []int) {
	return file_staff_v1_staff_proto_rawDescGZIP(), []int{10}
}

func (x *AddScheduleRequest) GetBarberId() string {
	if x != nil {
		return x.BarberId
	}
	return ""
}

func (x *AddScheduleRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *AddScheduleRequest) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *AddScheduleRequest) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

type GetScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BarberId      string                 `protobuf:"bytes,1,opt,name=barber_id,json=barberId,proto3" json:"barber_id,omitempty"`
	Week          string                 `protobuf:"bytes,2,opt,name=week,proto3" json:"week,omitempty"` // ISO week: "2026-W08"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScheduleRequest) Reset() {
	*x = GetScheduleRequest{}
	mi := &file_staff_v1_staff_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScheduleRequest) ProtoMessage() {}

func (x *GetScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staff_v1_staff_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScheduleRequest.ProtoReflect.Descriptor instead.
func (*GetScheduleRequest) Descriptor() ([]byte, []int) {
	return file_staff_v1_staff_proto_rawDescGZIP(), []int{11}
}

func (x *GetScheduleRequest) GetBarberId() string {
	if x != nil {
		return x.BarberId
	}
	return ""
}

func (x *GetScheduleRequest) GetWeek() string {
	if x != nil {
		return x.Week
	}
	return ""
}

type GetScheduleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Week          string                 `protobuf:"bytes,1,opt,name=week,proto3" json:"week,omitempty"`
	Days          []*ScheduleDay         `protobuf:"bytes,2,rep,name=days,proto3" json:"days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScheduleResponse) Reset() {
	*x = GetScheduleResponse{}
	mi := &file_staff_v1_staff_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScheduleResponse) ProtoMessage() {}

func (x *GetScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_staff_v1_staff_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScheduleResponse.ProtoReflect.Descriptor instead.
func (*GetScheduleResponse) Descriptor() ([]byte, []int) {
	return file_staff_v1_staff_proto_rawDescGZIP(), []int{12}
}

func (x *GetScheduleResponse) GetWeek() string {
	if x != nil {
		return x.Week
	}
	return ""
}

func (x *GetScheduleResponse) GetDays() []*ScheduleDay {
	if x != nil {
		return x.Days
	}
	return nil
}

type ListServicesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BarberId        string                 `protobuf:"bytes,1,opt,name=barber_id,json=barberId,proto3" json:"barber_id,omitempty"`
	IncludeInactive bool                   `protobuf:"varint,2,opt,name=include_inactive,json=includeInactive,proto3" json:"include_inactive,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListServicesRequest) Reset() {
	*x = ListServicesRequest{}
	mi := &file_staff_v1_staff_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesRequest) ProtoMessage() {}

func (x *ListServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staff_v1_staff_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesRequest.ProtoReflect.Descriptor instead.
func (*ListServicesRequest) Descriptor() ([]byte, []int) {
	return file_staff_v1_staff_proto_rawDescGZIP(), []int{13}
}

func (x *ListServicesRequest) GetBarberId() string {
	if x != nil {
		return x.BarberId
	}
	return ""
}

func (x *ListServicesRequest) GetIncludeInactive() bool {
	if x != nil {
		return x.IncludeInactive
	}
	return false
}

type ListServicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*ServiceResponse     `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesResponse) Reset() {
	*x = ListServicesResponse{}
	mi := &file_staff_v1_staff_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesResponse) ProtoMessage() {}

func (x *ListServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_staff_v1_staff_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesResponse.ProtoReflect.Descriptor instead.
func (*ListServicesResponse) Descriptor() ([]byte, []int) {
	return file_staff_v1_staff_proto_rawDescGZIP(), []int{14}
}

func (x *ListServicesResponse) GetServices() []*ServiceResponse {
	if x != nil {
		return x.Services
	}
	return nil
}

type CreateServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BarberId      string                 `protobuf:"bytes,1,opt,name=barber_id,json=barberId,proto3" json:"barber_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         int32                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateServiceRequest) Reset() {
	*x = CreateServiceRequest{}
	mi := &file_staff_v1_staff_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServiceRequest) ProtoMessage() {}

func (x *CreateServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staff_v1_staff_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServiceRequest.ProtoReflect.Descriptor instead.
func (*CreateServiceRequest) Descriptor() ([]byte, []int) {
	return file_staff_v1_staff_proto_rawDescGZIP(), []int{15}
}

func (x *CreateServiceRequest) GetBarberId() string {
	if x != nil {
		return x.BarberId
	}
	return ""
}

func (x *CreateServiceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateServiceRequest) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type UpdateServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BarberId      string                 `protobuf:"bytes,2,opt,name=barber_id,json=barberId,proto3" json:"barber_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Price         int32                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	IsActive      bool                   `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateServiceRequest) Reset() {
	*x = UpdateServiceRequest{}
	mi := &file_staff_v1_staff_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServiceRequest) ProtoMessage() {}

func (x *UpdateServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staff_v1_staff_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServiceRequest.ProtoReflect.Descriptor instead.
func (*UpdateServiceRequest) Descriptor() ([]byte, []int) {
	return file_staff_v1_staff_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateServiceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateServiceRequest) GetBarberId() string {
	if x != nil {
		return x.BarberId
	}
	return ""
}

func (x *UpdateServiceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateServiceRequest) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateServiceRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type DeleteServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BarberId      string                 `protobuf:"bytes,2,opt,name=barber_id,json=barberId,proto3" json:"barber_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteServiceRequest) Reset() {
	*x = DeleteServiceRequest{}
	mi := &file_staff_v1_staff_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServiceRequest) ProtoMessage() {}

func (x *DeleteServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staff_v1_staff_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServiceRequest.ProtoReflect.Descriptor instead.
func (*DeleteServiceRequest) Descriptor() ([]byte, []int) {
	return file_staff_v1_staff_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteServiceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteServiceRequest) GetBarberId() string {
	if x != nil {
		return x.BarberId
	}
	return ""
}

type ServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         int32                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	IsActive      bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceResponse) Reset() {
	*x = ServiceResponse{}
	mi := &file_staff_v1_staff_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceResponse) ProtoMessage() {}

func (x *ServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_staff_v1_staff_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceResponse.ProtoReflect.Descriptor instead.
func (*ServiceResponse) Descriptor() ([]byte, []int) {
	return file_staff_v1_staff_proto_rawDescGZIP(), []int{18}
}

func (x *ServiceResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServiceResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceResponse) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ServiceResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

// ScheduleEvent отправляется при добавлении или удалении рабочего дня барбера.
type ScheduleEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScheduleId    string                 `protobuf:"bytes,1,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	BarberId      string                 `protobuf:"bytes,2,opt,name=barber_id,json=barberId,proto3" json:"barber_id,omitempty"`
	Date          string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`                            // YYYY-MM-DD
	StartTime     string                 `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // HH:MM
	EndTime       string                 `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`       // HH:MM
	EventType     ScheduleEventType      `protobuf:"varint,6,opt,name=event_type,json=eventType,proto3,enum=staff.v1.ScheduleEventType" json:"event_type,omitempty"`
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleEvent) Reset() {
	*x = ScheduleEvent{}
	mi := &file_staff_v1_staff_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleEvent) ProtoMessage() {}

func (x *ScheduleEvent) ProtoReflect() protoreflect.Message {
	mi := &file_staff_v1_staff_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleEvent.ProtoReflect.Descriptor instead.
func (*ScheduleEvent) Descriptor() ([]byte, []int) {
	return file_staff_v1_staff_proto_rawDescGZIP(), []int{19}
}

func (x *ScheduleEvent) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

func (x *ScheduleEvent) GetBarberId() string {
	if x != nil {
		return x.BarberId
	}
	return ""
}

func (x *ScheduleEvent) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *ScheduleEvent) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *ScheduleEvent) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *ScheduleEvent) GetEventType() ScheduleEventType {
	if x != nil {
		return x.EventType
	}
	return ScheduleEventType_SCHEDULE_EVENT_UNSPECIFIED
}

func (x *ScheduleEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

var File_staff_v1_staff_proto protoreflect.FileDescriptor

const file_staff_v1_staff_proto_rawDesc = "" +
	"\n" +
	"\x14staff/v1/staff.proto\x12\bstaff.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xa8\x01\n" +
	"\rLoginResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x05R\texpiresIn\x120\n" +
	"\x06barber\x18\x04 \x01(\v2\x18.staff.v1.BarberResponseR\x06barber\"4\n" +
	"\rLogoutRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\":\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"}\n" +
	"\x14RefreshTokenResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x05R\texpiresIn\"\"\n" +
	"\x10GetBarberRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xc8\x01\n" +
	"\x0eBarberResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tphoto_url\x18\x03 \x01(\tR\bphotoUrl\x12&\n" +
	"\x0especialization\x18\x04 \x01(\tR\x0especialization\x12\x16\n" +
	"\x06rating\x18\x05 \x01(\x01R\x06rating\x125\n" +
	"\bservices\x18\x06 \x03(\v2\x19.staff.v1.ServiceResponseR\bservices\"\x14\n" +
	"\x12ListBarbersRequest\"I\n" +
	"\x13ListBarbersResponse\x122\n" +
	"\abarbers\x18\x01 \x03(\v2\x18.staff.v1.BarberResponseR\abarbers\"\x88\x01\n" +
	"\vScheduleDay\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tbarber_id\x18\x02 \x01(\tR\bbarberId\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\tR\aendTime\"\x7f\n" +
	"\x12AddScheduleRequest\x12\x1b\n" +
	"\tbarber_id\x18\x01 \x01(\tR\bbarberId\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x1d\n" +
	"\n" +
	"start_time\x18\x03 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x04 \x01(\tR\aendTime\"E\n" +
	"\x12GetScheduleRequest\x12\x1b\n" +
	"\tbarber_id\x18\x01 \x01(\tR\bbarberId\x12\x12\n" +
	"\x04week\x18\x02 \x01(\tR\x04week\"T\n" +
	"\x13GetScheduleResponse\x12\x12\n" +
	"\x04week\x18\x01 \x01(\tR\x04week\x12)\n" +
	"\x04days\x18\x02 \x03(\v2\x15.staff.v1.ScheduleDayR\x04days\"]\n" +
	"\x13ListServicesRequest\x12\x1b\n" +
	"\tbarber_id\x18\x01 \x01(\tR\bbarberId\x12)\n" +
	"\x10include_inactive\x18\x02 \x01(\bR\x0fincludeInactive\"M\n" +
	"\x14ListServicesResponse\x125\n" +
	"\bservices\x18\x01 \x03(\v2\x19.staff.v1.ServiceResponseR\bservices\"]\n" +
	"\x14CreateServiceRequest\x12\x1b\n" +
	"\tbarber_id\x18\x01 \x01(\tR\bbarberId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x05R\x05price\"\x8a\x01\n" +
	"\x14UpdateServiceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tbarber_id\x18\x02 \x01(\tR\bbarberId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x05R\x05price\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActive\"C\n" +
	"\x14DeleteServiceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tbarber_id\x18\x02 \x01(\tR\bbarberId\"h\n" +
	"\x0fServiceResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x05R\x05price\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\"\x94\x02\n" +
	"\rScheduleEvent\x12\x1f\n" +
	"\vschedule_id\x18\x01 \x01(\tR\n" +
	"scheduleId\x12\x1b\n" +
	"\tbarber_id\x18\x02 \x01(\tR\bbarberId\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\tR\aendTime\x12:\n" +
	"\n" +
	"event_type\x18\x06 \x01(\x0e2\x1b.staff.v1.ScheduleEventTypeR\teventType\x12;\n" +
	"\voccurred_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt*i\n" +
	"\x11ScheduleEventType\x12\x1e\n" +
	"\x1aSCHEDULE_EVENT_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14SCHEDULE_EVENT_ADDED\x10\x01\x12\x1a\n" +
	"\x16SCHEDULE_EVENT_DELETED\x10\x022\xa1\x06\n" +
	"\fStaffService\x128\n" +
	"\x05Login\x12\x16.staff.v1.LoginRequest\x1a\x17.staff.v1.LoginResponse\x129\n" +
	"\x06Logout\x12\x17.staff.v1.LogoutRequest\x1a\x16.google.protobuf.Empty\x12M\n" +
	"\fRefreshToken\x12\x1d.staff.v1.RefreshTokenRequest\x1a\x1e.staff.v1.RefreshTokenResponse\x12A\n" +
	"\tGetBarber\x12\x1a.staff.v1.GetBarberRequest\x1a\x18.staff.v1.BarberResponse\x12J\n" +
	"\vListBarbers\x12\x1c.staff.v1.ListBarbersRequest\x1a\x1d.staff.v1.ListBarbersResponse\x12J\n" +
	"\vGetSchedule\x12\x1c.staff.v1.GetScheduleRequest\x1a\x1d.staff.v1.GetScheduleResponse\x12B\n" +
	"\vAddSchedule\x12\x1c.staff.v1.AddScheduleRequest\x1a\x15.staff.v1.ScheduleDay\x12M\n" +
	"\fListServices\x12\x1d.staff.v1.ListServicesRequest\x1a\x1e.staff.v1.ListServicesResponse\x12J\n" +
	"\rCreateService\x12\x1e.staff.v1.CreateServiceRequest\x1a\x19.staff.v1.ServiceResponse\x12J\n" +
	"\rUpdateService\x12\x1e.staff.v1.UpdateServiceRequest\x1a\x19.staff.v1.ServiceResponse\x12G\n" +
	"\rDeleteService\x12\x1e.staff.v1.DeleteServiceRequest\x1a\x16.google.protobuf.EmptyBBZ@github.com/RomanKovalev007/barber_crm/api/proto/staff/v1;staffv1b\x06proto3"

var (
	file_staff_v1_staff_proto_rawDescOnce sync.Once
	file_staff_v1_staff_proto_rawDescData []byte
)

func file_staff_v1_staff_proto_rawDescGZIP() []byte {
	file_staff_v1_staff_proto_rawDescOnce.Do(func() {
		file_staff_v1_staff_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_staff_v1_staff_proto_rawDesc), len(file_staff_v1_staff_proto_rawDesc)))
	})
	return file_staff_v1_staff_proto_rawDescData
}

var file_staff_v1_staff_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_staff_v1_staff_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_staff_v1_staff_proto_goTypes = []any{
	(ScheduleEventType)(0),        // 0: staff.v1.ScheduleEventType
	(*LoginRequest)(nil),          // 1: staff.v1.LoginRequest
	(*LoginResponse)(nil),         // 2: staff.v1.LoginResponse
	(*LogoutRequest)(nil),         // 3: staff.v1.LogoutRequest
	(*RefreshTokenRequest)(nil),   // 4: staff.v1.RefreshTokenRequest
	(*RefreshTokenResponse)(nil),  // 5: staff.v1.RefreshTokenResponse
	(*GetBarberRequest)(nil),      // 6: staff.v1.GetBarberRequest
	(*BarberResponse)(nil),        // 7: staff.v1.BarberResponse
	(*ListBarbersRequest)(nil),    // 8: staff.v1.ListBarbersRequest
	(*ListBarbersResponse)(nil),   // 9: staff.v1.ListBarbersResponse
	(*ScheduleDay)(nil),           // 10: staff.v1.ScheduleDay
	(*AddScheduleRequest)(nil),    // 11: staff.v1.AddScheduleRequest
	(*GetScheduleRequest)(nil),    // 12: staff.v1.GetScheduleRequest
	(*GetScheduleResponse)(nil),   // 13: staff.v1.GetScheduleResponse
	(*ListServicesRequest)(nil),   // 14: staff.v1.ListServicesRequest
	(*ListServicesResponse)(nil),  // 15: staff.v1.ListServicesResponse
	(*CreateServiceRequest)(nil),  // 16: staff.v1.CreateServiceRequest
	(*UpdateServiceRequest)(nil),  // 17: staff.v1.UpdateServiceRequest
	(*DeleteServiceRequest)(nil),  // 18: staff.v1.DeleteServiceRequest
	(*ServiceResponse)(nil),       // 19: staff.v1.ServiceResponse
	(*ScheduleEvent)(nil),         // 20: staff.v1.ScheduleEvent
	(*timestamppb.Timestamp)(nil), // 21: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 22: google.protobuf.Empty
}
var file_staff_v1_staff_proto_depIdxs = []int32{
	7,  // 0: staff.v1.LoginResponse.barber:type_name -> staff.v1.BarberResponse
	19, // 1: staff.v1.BarberResponse.services:type_name -> staff.v1.ServiceResponse
	7,  // 2: staff.v1.ListBarbersResponse.barbers:type_name -> staff.v1.BarberResponse
	10, // 3: staff.v1.GetScheduleResponse.days:type_name -> staff.v1.ScheduleDay
	19, // 4: staff.v1.ListServicesResponse.services:type_name -> staff.v1.ServiceResponse
	0,  // 5: staff.v1.ScheduleEvent.event_type:type_name -> staff.v1.ScheduleEventType
	21, // 6: staff.v1.ScheduleEvent.occurred_at:type_name -> google.protobuf.Timestamp
	1,  // 7: staff.v1.StaffService.Login:input_type -> staff.v1.LoginRequest
	3,  // 8: staff.v1.StaffService.Logout:input_type -> staff.v1.LogoutRequest
	4,  // 9: staff.v1.StaffService.RefreshToken:input_type -> staff.v1.RefreshTokenRequest
	6,  // 10: staff.v1.StaffService.GetBarber:input_type -> staff.v1.GetBarberRequest
	8,  // 11: staff.v1.StaffService.ListBarbers:input_type -> staff.v1.ListBarbersRequest
	12, // 12: staff.v1.StaffService.GetSchedule:input_type -> staff.v1.GetScheduleRequest
	11, // 13: staff.v1.StaffService.AddSchedule:input_type -> staff.v1.AddScheduleRequest
	14, // 14: staff.v1.StaffService.ListServices:input_type -> staff.v1.ListServicesRequest
	16, // 15: staff.v1.StaffService.CreateService:input_type -> staff.v1.CreateServiceRequest
	17, // 16: staff.v1.StaffService.UpdateService:input_type -> staff.v1.UpdateServiceRequest
	18, // 17: staff.v1.StaffService.DeleteService:input_type -> staff.v1.DeleteServiceRequest
	2,  // 18: staff.v1.StaffService.Login:output_type -> staff.v1.LoginResponse
	22, // 19: staff.v1.StaffService.Logout:output_type -> google.protobuf.Empty
	5,  // 20: staff.v1.StaffService.RefreshToken:output_type -> staff.v1.RefreshTokenResponse
	7,  // 21: staff.v1.StaffService.GetBarber:output_type -> staff.v1.BarberResponse
	9,  // 22: staff.v1.StaffService.ListBarbers:output_type -> staff.v1.ListBarbersResponse
	13, // 23: staff.v1.StaffService.GetSchedule:output_type -> staff.v1.GetScheduleResponse
	10, // 24: staff.v1.StaffService.AddSchedule:output_type -> staff.v1.ScheduleDay
	15, // 25: staff.v1.StaffService.ListServices:output_type -> staff.v1.ListServicesResponse
	19, // 26: staff.v1.StaffService.CreateService:output_type -> staff.v1.ServiceResponse
	19, // 27: staff.v1.StaffService.UpdateService:output_type -> staff.v1.ServiceResponse
	22, // 28: staff.v1.StaffService.DeleteService:output_type -> google.protobuf.Empty
	18, // [18:29] is the sub-list for method output_type
	7,  // [7:18] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_staff_v1_staff_proto_init() }
func file_staff_v1_staff_proto_init() {
	if File_staff_v1_staff_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_staff_v1_staff_proto_rawDesc), len(file_staff_v1_staff_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_staff_v1_staff_proto_goTypes,
		DependencyIndexes: file_staff_v1_staff_proto_depIdxs,
		EnumInfos:         file_staff_v1_staff_proto_enumTypes,
		MessageInfos:      file_staff_v1_staff_proto_msgTypes,
	}.Build()
	File_staff_v1_staff_proto = out.File
	file_staff_v1_staff_proto_goTypes = nil
	file_staff_v1_staff_proto_depIdxs = nil
}
