// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/staff/v1/staff.proto

package staffv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PartOfDay int32

const (
	PartOfDay_PART_OF_DAY_UNSPECIFIED PartOfDay = 0
	PartOfDay_PART_OF_DAY_AM          PartOfDay = 1
	PartOfDay_PART_OF_DAY_PM          PartOfDay = 2
)

// Enum value maps for PartOfDay.
var (
	PartOfDay_name = map[int32]string{
		0: "PART_OF_DAY_UNSPECIFIED",
		1: "PART_OF_DAY_AM",
		2: "PART_OF_DAY_PM",
	}
	PartOfDay_value = map[string]int32{
		"PART_OF_DAY_UNSPECIFIED": 0,
		"PART_OF_DAY_AM":          1,
		"PART_OF_DAY_PM":          2,
	}
)

func (x PartOfDay) Enum() *PartOfDay {
	p := new(PartOfDay)
	*p = x
	return p
}

func (x PartOfDay) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PartOfDay) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_staff_v1_staff_proto_enumTypes[0].Descriptor()
}

func (PartOfDay) Type() protoreflect.EnumType {
	return &file_proto_staff_v1_staff_proto_enumTypes[0]
}

func (x PartOfDay) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PartOfDay.Descriptor instead.
func (PartOfDay) EnumDescriptor() ([]byte, []int) {
	return file_proto_staff_v1_staff_proto_rawDescGZIP(), []int{0}
}

type ScheduleEventType int32

const (
	ScheduleEventType_SCHEDULE_EVENT_UNSPECIFIED ScheduleEventType = 0
	ScheduleEventType_SCHEDULE_EVENT_ADDED       ScheduleEventType = 1
	ScheduleEventType_SCHEDULE_EVENT_DELETED     ScheduleEventType = 2
)

// Enum value maps for ScheduleEventType.
var (
	ScheduleEventType_name = map[int32]string{
		0: "SCHEDULE_EVENT_UNSPECIFIED",
		1: "SCHEDULE_EVENT_ADDED",
		2: "SCHEDULE_EVENT_DELETED",
	}
	ScheduleEventType_value = map[string]int32{
		"SCHEDULE_EVENT_UNSPECIFIED": 0,
		"SCHEDULE_EVENT_ADDED":       1,
		"SCHEDULE_EVENT_DELETED":     2,
	}
)

func (x ScheduleEventType) Enum() *ScheduleEventType {
	p := new(ScheduleEventType)
	*p = x
	return p
}

func (x ScheduleEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScheduleEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_staff_v1_staff_proto_enumTypes[1].Descriptor()
}

func (ScheduleEventType) Type() protoreflect.EnumType {
	return &file_proto_staff_v1_staff_proto_enumTypes[1]
}

func (x ScheduleEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScheduleEventType.Descriptor instead.
func (ScheduleEventType) EnumDescriptor() ([]byte, []int) {
	return file_proto_staff_v1_staff_proto_rawDescGZIP(), []int{1}
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_proto_staff_v1_staff_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staff_v1_staff_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_staff_v1_staff_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresIn     int32                  `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"` // секунды
	Barber        *BarberResponse        `protobuf:"bytes,4,opt,name=barber,proto3" json:"barber,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_proto_staff_v1_staff_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staff_v1_staff_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_staff_v1_staff_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginResponse) GetExpiresIn() int32 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *LoginResponse) GetBarber() *BarberResponse {
	if x != nil {
		return x.Barber
	}
	return nil
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_proto_staff_v1_staff_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staff_v1_staff_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_proto_staff_v1_staff_proto_rawDescGZIP(), []int{2}
}

func (x *LogoutRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_proto_staff_v1_staff_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staff_v1_staff_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_staff_v1_staff_proto_rawDescGZIP(), []int{3}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresIn     int32                  `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_proto_staff_v1_staff_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staff_v1_staff_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_staff_v1_staff_proto_rawDescGZIP(), []int{4}
}

func (x *RefreshTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshTokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshTokenResponse) GetExpiresIn() int32 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

type GetBarberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BarberId      string                 `protobuf:"bytes,1,opt,name=barber_id,json=barberId,proto3" json:"barber_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBarberRequest) Reset() {
	*x = GetBarberRequest{}
	mi := &file_proto_staff_v1_staff_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBarberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBarberRequest) ProtoMessage() {}

func (x *GetBarberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staff_v1_staff_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBarberRequest.ProtoReflect.Descriptor instead.
func (*GetBarberRequest) Descriptor() ([]byte, []int) {
	return file_proto_staff_v1_staff_proto_rawDescGZIP(), []int{5}
}

func (x *GetBarberRequest) GetBarberId() string {
	if x != nil {
		return x.BarberId
	}
	return ""
}

type BarberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BarberId      string                 `protobuf:"bytes,1,opt,name=barber_id,json=barberId,proto3" json:"barber_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Services      []*ServiceResponse     `protobuf:"bytes,3,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BarberResponse) Reset() {
	*x = BarberResponse{}
	mi := &file_proto_staff_v1_staff_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BarberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BarberResponse) ProtoMessage() {}

func (x *BarberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staff_v1_staff_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BarberResponse.ProtoReflect.Descriptor instead.
func (*BarberResponse) Descriptor() ([]byte, []int) {
	return file_proto_staff_v1_staff_proto_rawDescGZIP(), []int{6}
}

func (x *BarberResponse) GetBarberId() string {
	if x != nil {
		return x.BarberId
	}
	return ""
}

func (x *BarberResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BarberResponse) GetServices() []*ServiceResponse {
	if x != nil {
		return x.Services
	}
	return nil
}

type ListBarbersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBarbersRequest) Reset() {
	*x = ListBarbersRequest{}
	mi := &file_proto_staff_v1_staff_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBarbersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBarbersRequest) ProtoMessage() {}

func (x *ListBarbersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staff_v1_staff_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBarbersRequest.ProtoReflect.Descriptor instead.
func (*ListBarbersRequest) Descriptor() ([]byte, []int) {
	return file_proto_staff_v1_staff_proto_rawDescGZIP(), []int{7}
}

func (x *ListBarbersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListBarbersRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListBarbersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Barbers       []*BarberResponse      `protobuf:"bytes,1,rep,name=barbers,proto3" json:"barbers,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBarbersResponse) Reset() {
	*x = ListBarbersResponse{}
	mi := &file_proto_staff_v1_staff_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBarbersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBarbersResponse) ProtoMessage() {}

func (x *ListBarbersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staff_v1_staff_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBarbersResponse.ProtoReflect.Descriptor instead.
func (*ListBarbersResponse) Descriptor() ([]byte, []int) {
	return file_proto_staff_v1_staff_proto_rawDescGZIP(), []int{8}
}

func (x *ListBarbersResponse) GetBarbers() []*BarberResponse {
	if x != nil {
		return x.Barbers
	}
	return nil
}

func (x *ListBarbersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ScheduleDay struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScheduleDayId string                 `protobuf:"bytes,1,opt,name=schedule_day_id,json=scheduleDayId,proto3" json:"schedule_day_id,omitempty"`
	BarberId      string                 `protobuf:"bytes,2,opt,name=barber_id,json=barberId,proto3" json:"barber_id,omitempty"`
	Date          string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`                            // YYYY-MM-DD
	StartTime     string                 `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // HH:MM
	EndTime       string                 `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`       // HH:MM
	PartOfDay     PartOfDay              `protobuf:"varint,6,opt,name=part_of_day,json=partOfDay,proto3,enum=staff.v1.PartOfDay" json:"part_of_day,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleDay) Reset() {
	*x = ScheduleDay{}
	mi := &file_proto_staff_v1_staff_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleDay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleDay) ProtoMessage() {}

func (x *ScheduleDay) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staff_v1_staff_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleDay.ProtoReflect.Descriptor instead.
func (*ScheduleDay) Descriptor() ([]byte, []int) {
	return file_proto_staff_v1_staff_proto_rawDescGZIP(), []int{9}
}

func (x *ScheduleDay) GetScheduleDayId() string {
	if x != nil {
		return x.ScheduleDayId
	}
	return ""
}

func (x *ScheduleDay) GetBarberId() string {
	if x != nil {
		return x.BarberId
	}
	return ""
}

func (x *ScheduleDay) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *ScheduleDay) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *ScheduleDay) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *ScheduleDay) GetPartOfDay() PartOfDay {
	if x != nil {
		return x.PartOfDay
	}
	return PartOfDay_PART_OF_DAY_UNSPECIFIED
}

type GetScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BarberId      string                 `protobuf:"bytes,1,opt,name=barber_id,json=barberId,proto3" json:"barber_id,omitempty"`
	Week          string                 `protobuf:"bytes,2,opt,name=week,proto3" json:"week,omitempty"` // ISO week: "2026-W10"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScheduleRequest) Reset() {
	*x = GetScheduleRequest{}
	mi := &file_proto_staff_v1_staff_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScheduleRequest) ProtoMessage() {}

func (x *GetScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staff_v1_staff_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScheduleRequest.ProtoReflect.Descriptor instead.
func (*GetScheduleRequest) Descriptor() ([]byte, []int) {
	return file_proto_staff_v1_staff_proto_rawDescGZIP(), []int{10}
}

func (x *GetScheduleRequest) GetBarberId() string {
	if x != nil {
		return x.BarberId
	}
	return ""
}

func (x *GetScheduleRequest) GetWeek() string {
	if x != nil {
		return x.Week
	}
	return ""
}

type GetScheduleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Week          string                 `protobuf:"bytes,1,opt,name=week,proto3" json:"week,omitempty"`
	Days          []*ScheduleDay         `protobuf:"bytes,2,rep,name=days,proto3" json:"days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScheduleResponse) Reset() {
	*x = GetScheduleResponse{}
	mi := &file_proto_staff_v1_staff_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScheduleResponse) ProtoMessage() {}

func (x *GetScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staff_v1_staff_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScheduleResponse.ProtoReflect.Descriptor instead.
func (*GetScheduleResponse) Descriptor() ([]byte, []int) {
	return file_proto_staff_v1_staff_proto_rawDescGZIP(), []int{11}
}

func (x *GetScheduleResponse) GetWeek() string {
	if x != nil {
		return x.Week
	}
	return ""
}

func (x *GetScheduleResponse) GetDays() []*ScheduleDay {
	if x != nil {
		return x.Days
	}
	return nil
}

type UpsertScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BarberId      string                 `protobuf:"bytes,1,opt,name=barber_id,json=barberId,proto3" json:"barber_id,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`                            // YYYY-MM-DD
	StartTime     string                 `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // HH:MM
	EndTime       string                 `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`       // HH:MM
	PartOfDay     PartOfDay              `protobuf:"varint,5,opt,name=part_of_day,json=partOfDay,proto3,enum=staff.v1.PartOfDay" json:"part_of_day,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertScheduleRequest) Reset() {
	*x = UpsertScheduleRequest{}
	mi := &file_proto_staff_v1_staff_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertScheduleRequest) ProtoMessage() {}

func (x *UpsertScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staff_v1_staff_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertScheduleRequest.ProtoReflect.Descriptor instead.
func (*UpsertScheduleRequest) Descriptor() ([]byte, []int) {
	return file_proto_staff_v1_staff_proto_rawDescGZIP(), []int{12}
}

func (x *UpsertScheduleRequest) GetBarberId() string {
	if x != nil {
		return x.BarberId
	}
	return ""
}

func (x *UpsertScheduleRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *UpsertScheduleRequest) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *UpsertScheduleRequest) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *UpsertScheduleRequest) GetPartOfDay() PartOfDay {
	if x != nil {
		return x.PartOfDay
	}
	return PartOfDay_PART_OF_DAY_UNSPECIFIED
}

type UpsertWeekScheduleRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	BarberId      string                   `protobuf:"bytes,1,opt,name=barber_id,json=barberId,proto3" json:"barber_id,omitempty"`
	Days          []*UpsertScheduleRequest `protobuf:"bytes,2,rep,name=days,proto3" json:"days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertWeekScheduleRequest) Reset() {
	*x = UpsertWeekScheduleRequest{}
	mi := &file_proto_staff_v1_staff_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertWeekScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertWeekScheduleRequest) ProtoMessage() {}

func (x *UpsertWeekScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staff_v1_staff_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertWeekScheduleRequest.ProtoReflect.Descriptor instead.
func (*UpsertWeekScheduleRequest) Descriptor() ([]byte, []int) {
	return file_proto_staff_v1_staff_proto_rawDescGZIP(), []int{13}
}

func (x *UpsertWeekScheduleRequest) GetBarberId() string {
	if x != nil {
		return x.BarberId
	}
	return ""
}

func (x *UpsertWeekScheduleRequest) GetDays() []*UpsertScheduleRequest {
	if x != nil {
		return x.Days
	}
	return nil
}

type UpsertWeekScheduleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Days          []*ScheduleDay         `protobuf:"bytes,1,rep,name=days,proto3" json:"days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertWeekScheduleResponse) Reset() {
	*x = UpsertWeekScheduleResponse{}
	mi := &file_proto_staff_v1_staff_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertWeekScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertWeekScheduleResponse) ProtoMessage() {}

func (x *UpsertWeekScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staff_v1_staff_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertWeekScheduleResponse.ProtoReflect.Descriptor instead.
func (*UpsertWeekScheduleResponse) Descriptor() ([]byte, []int) {
	return file_proto_staff_v1_staff_proto_rawDescGZIP(), []int{14}
}

func (x *UpsertWeekScheduleResponse) GetDays() []*ScheduleDay {
	if x != nil {
		return x.Days
	}
	return nil
}

type DeleteScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BarberId      string                 `protobuf:"bytes,1,opt,name=barber_id,json=barberId,proto3" json:"barber_id,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"` // YYYY-MM-DD
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteScheduleRequest) Reset() {
	*x = DeleteScheduleRequest{}
	mi := &file_proto_staff_v1_staff_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteScheduleRequest) ProtoMessage() {}

func (x *DeleteScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staff_v1_staff_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteScheduleRequest.ProtoReflect.Descriptor instead.
func (*DeleteScheduleRequest) Descriptor() ([]byte, []int) {
	return file_proto_staff_v1_staff_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteScheduleRequest) GetBarberId() string {
	if x != nil {
		return x.BarberId
	}
	return ""
}

func (x *DeleteScheduleRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type GetServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	BarberId      string                 `protobuf:"bytes,2,opt,name=barber_id,json=barberId,proto3" json:"barber_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceRequest) Reset() {
	*x = GetServiceRequest{}
	mi := &file_proto_staff_v1_staff_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceRequest) ProtoMessage() {}

func (x *GetServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staff_v1_staff_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceRequest.ProtoReflect.Descriptor instead.
func (*GetServiceRequest) Descriptor() ([]byte, []int) {
	return file_proto_staff_v1_staff_proto_rawDescGZIP(), []int{16}
}

func (x *GetServiceRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *GetServiceRequest) GetBarberId() string {
	if x != nil {
		return x.BarberId
	}
	return ""
}

type ListServicesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BarberId        string                 `protobuf:"bytes,1,opt,name=barber_id,json=barberId,proto3" json:"barber_id,omitempty"`
	IncludeInactive bool                   `protobuf:"varint,2,opt,name=include_inactive,json=includeInactive,proto3" json:"include_inactive,omitempty"`
	Limit           int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset          int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListServicesRequest) Reset() {
	*x = ListServicesRequest{}
	mi := &file_proto_staff_v1_staff_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesRequest) ProtoMessage() {}

func (x *ListServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staff_v1_staff_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesRequest.ProtoReflect.Descriptor instead.
func (*ListServicesRequest) Descriptor() ([]byte, []int) {
	return file_proto_staff_v1_staff_proto_rawDescGZIP(), []int{17}
}

func (x *ListServicesRequest) GetBarberId() string {
	if x != nil {
		return x.BarberId
	}
	return ""
}

func (x *ListServicesRequest) GetIncludeInactive() bool {
	if x != nil {
		return x.IncludeInactive
	}
	return false
}

func (x *ListServicesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListServicesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListServicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*ServiceResponse     `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesResponse) Reset() {
	*x = ListServicesResponse{}
	mi := &file_proto_staff_v1_staff_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesResponse) ProtoMessage() {}

func (x *ListServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staff_v1_staff_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesResponse.ProtoReflect.Descriptor instead.
func (*ListServicesResponse) Descriptor() ([]byte, []int) {
	return file_proto_staff_v1_staff_proto_rawDescGZIP(), []int{18}
}

func (x *ListServicesResponse) GetServices() []*ServiceResponse {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *ListServicesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CreateServiceRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BarberId        string                 `protobuf:"bytes,1,opt,name=barber_id,json=barberId,proto3" json:"barber_id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price           int32                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	DurationMinutes int32                  `protobuf:"varint,4,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"` // кратно 15
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateServiceRequest) Reset() {
	*x = CreateServiceRequest{}
	mi := &file_proto_staff_v1_staff_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServiceRequest) ProtoMessage() {}

func (x *CreateServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staff_v1_staff_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServiceRequest.ProtoReflect.Descriptor instead.
func (*CreateServiceRequest) Descriptor() ([]byte, []int) {
	return file_proto_staff_v1_staff_proto_rawDescGZIP(), []int{19}
}

func (x *CreateServiceRequest) GetBarberId() string {
	if x != nil {
		return x.BarberId
	}
	return ""
}

func (x *CreateServiceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateServiceRequest) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateServiceRequest) GetDurationMinutes() int32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

type UpdateServiceRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ServiceId       string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	BarberId        string                 `protobuf:"bytes,2,opt,name=barber_id,json=barberId,proto3" json:"barber_id,omitempty"`
	Name            string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Price           int32                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	DurationMinutes int32                  `protobuf:"varint,5,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
	IsActive        bool                   `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateServiceRequest) Reset() {
	*x = UpdateServiceRequest{}
	mi := &file_proto_staff_v1_staff_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServiceRequest) ProtoMessage() {}

func (x *UpdateServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staff_v1_staff_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServiceRequest.ProtoReflect.Descriptor instead.
func (*UpdateServiceRequest) Descriptor() ([]byte, []int) {
	return file_proto_staff_v1_staff_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateServiceRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *UpdateServiceRequest) GetBarberId() string {
	if x != nil {
		return x.BarberId
	}
	return ""
}

func (x *UpdateServiceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateServiceRequest) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateServiceRequest) GetDurationMinutes() int32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

func (x *UpdateServiceRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type DeleteServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	BarberId      string                 `protobuf:"bytes,2,opt,name=barber_id,json=barberId,proto3" json:"barber_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteServiceRequest) Reset() {
	*x = DeleteServiceRequest{}
	mi := &file_proto_staff_v1_staff_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServiceRequest) ProtoMessage() {}

func (x *DeleteServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staff_v1_staff_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServiceRequest.ProtoReflect.Descriptor instead.
func (*DeleteServiceRequest) Descriptor() ([]byte, []int) {
	return file_proto_staff_v1_staff_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteServiceRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *DeleteServiceRequest) GetBarberId() string {
	if x != nil {
		return x.BarberId
	}
	return ""
}

type ServiceResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ServiceId       string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price           int32                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	DurationMinutes int32                  `protobuf:"varint,4,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
	IsActive        bool                   `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ServiceResponse) Reset() {
	*x = ServiceResponse{}
	mi := &file_proto_staff_v1_staff_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceResponse) ProtoMessage() {}

func (x *ServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staff_v1_staff_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceResponse.ProtoReflect.Descriptor instead.
func (*ServiceResponse) Descriptor() ([]byte, []int) {
	return file_proto_staff_v1_staff_proto_rawDescGZIP(), []int{22}
}

func (x *ServiceResponse) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ServiceResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceResponse) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ServiceResponse) GetDurationMinutes() int32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

func (x *ServiceResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

// ScheduleEvent отправляется при upsert или удалении рабочего дня барбера.
type ScheduleEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScheduleId    string                 `protobuf:"bytes,1,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	BarberId      string                 `protobuf:"bytes,2,opt,name=barber_id,json=barberId,proto3" json:"barber_id,omitempty"`
	Date          string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`                            // YYYY-MM-DD
	StartTime     string                 `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // HH:MM
	EndTime       string                 `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`       // HH:MM
	PartOfDay     PartOfDay              `protobuf:"varint,6,opt,name=part_of_day,json=partOfDay,proto3,enum=staff.v1.PartOfDay" json:"part_of_day,omitempty"`
	EventType     ScheduleEventType      `protobuf:"varint,7,opt,name=event_type,json=eventType,proto3,enum=staff.v1.ScheduleEventType" json:"event_type,omitempty"`
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleEvent) Reset() {
	*x = ScheduleEvent{}
	mi := &file_proto_staff_v1_staff_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleEvent) ProtoMessage() {}

func (x *ScheduleEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staff_v1_staff_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleEvent.ProtoReflect.Descriptor instead.
func (*ScheduleEvent) Descriptor() ([]byte, []int) {
	return file_proto_staff_v1_staff_proto_rawDescGZIP(), []int{23}
}

func (x *ScheduleEvent) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

func (x *ScheduleEvent) GetBarberId() string {
	if x != nil {
		return x.BarberId
	}
	return ""
}

func (x *ScheduleEvent) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *ScheduleEvent) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *ScheduleEvent) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *ScheduleEvent) GetPartOfDay() PartOfDay {
	if x != nil {
		return x.PartOfDay
	}
	return PartOfDay_PART_OF_DAY_UNSPECIFIED
}

func (x *ScheduleEvent) GetEventType() ScheduleEventType {
	if x != nil {
		return x.EventType
	}
	return ScheduleEventType_SCHEDULE_EVENT_UNSPECIFIED
}

func (x *ScheduleEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

var File_proto_staff_v1_staff_proto protoreflect.FileDescriptor

const file_proto_staff_v1_staff_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/staff/v1/staff.proto\x12\bstaff.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xa8\x01\n" +
	"\rLoginResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x05R\texpiresIn\x120\n" +
	"\x06barber\x18\x04 \x01(\v2\x18.staff.v1.BarberResponseR\x06barber\"4\n" +
	"\rLogoutRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\":\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"}\n" +
	"\x14RefreshTokenResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x05R\texpiresIn\"/\n" +
	"\x10GetBarberRequest\x12\x1b\n" +
	"\tbarber_id\x18\x01 \x01(\tR\bbarberId\"x\n" +
	"\x0eBarberResponse\x12\x1b\n" +
	"\tbarber_id\x18\x01 \x01(\tR\bbarberId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x125\n" +
	"\bservices\x18\x03 \x03(\v2\x19.staff.v1.ServiceResponseR\bservices\"B\n" +
	"\x12ListBarbersRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"_\n" +
	"\x13ListBarbersResponse\x122\n" +
	"\abarbers\x18\x01 \x03(\v2\x18.staff.v1.BarberResponseR\abarbers\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xd5\x01\n" +
	"\vScheduleDay\x12&\n" +
	"\x0fschedule_day_id\x18\x01 \x01(\tR\rscheduleDayId\x12\x1b\n" +
	"\tbarber_id\x18\x02 \x01(\tR\bbarberId\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\tR\aendTime\x123\n" +
	"\vpart_of_day\x18\x06 \x01(\x0e2\x13.staff.v1.PartOfDayR\tpartOfDay\"E\n" +
	"\x12GetScheduleRequest\x12\x1b\n" +
	"\tbarber_id\x18\x01 \x01(\tR\bbarberId\x12\x12\n" +
	"\x04week\x18\x02 \x01(\tR\x04week\"T\n" +
	"\x13GetScheduleResponse\x12\x12\n" +
	"\x04week\x18\x01 \x01(\tR\x04week\x12)\n" +
	"\x04days\x18\x02 \x03(\v2\x15.staff.v1.ScheduleDayR\x04days\"\xb7\x01\n" +
	"\x15UpsertScheduleRequest\x12\x1b\n" +
	"\tbarber_id\x18\x01 \x01(\tR\bbarberId\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x1d\n" +
	"\n" +
	"start_time\x18\x03 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x04 \x01(\tR\aendTime\x123\n" +
	"\vpart_of_day\x18\x05 \x01(\x0e2\x13.staff.v1.PartOfDayR\tpartOfDay\"m\n" +
	"\x19UpsertWeekScheduleRequest\x12\x1b\n" +
	"\tbarber_id\x18\x01 \x01(\tR\bbarberId\x123\n" +
	"\x04days\x18\x02 \x03(\v2\x1f.staff.v1.UpsertScheduleRequestR\x04days\"G\n" +
	"\x1aUpsertWeekScheduleResponse\x12)\n" +
	"\x04days\x18\x01 \x03(\v2\x15.staff.v1.ScheduleDayR\x04days\"H\n" +
	"\x15DeleteScheduleRequest\x12\x1b\n" +
	"\tbarber_id\x18\x01 \x01(\tR\bbarberId\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\"O\n" +
	"\x11GetServiceRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x1b\n" +
	"\tbarber_id\x18\x02 \x01(\tR\bbarberId\"\x8b\x01\n" +
	"\x13ListServicesRequest\x12\x1b\n" +
	"\tbarber_id\x18\x01 \x01(\tR\bbarberId\x12)\n" +
	"\x10include_inactive\x18\x02 \x01(\bR\x0fincludeInactive\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"c\n" +
	"\x14ListServicesResponse\x125\n" +
	"\bservices\x18\x01 \x03(\v2\x19.staff.v1.ServiceResponseR\bservices\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x88\x01\n" +
	"\x14CreateServiceRequest\x12\x1b\n" +
	"\tbarber_id\x18\x01 \x01(\tR\bbarberId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x05R\x05price\x12)\n" +
	"\x10duration_minutes\x18\x04 \x01(\x05R\x0fdurationMinutes\"\xc4\x01\n" +
	"\x14UpdateServiceRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x1b\n" +
	"\tbarber_id\x18\x02 \x01(\tR\bbarberId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x05R\x05price\x12)\n" +
	"\x10duration_minutes\x18\x05 \x01(\x05R\x0fdurationMinutes\x12\x1b\n" +
	"\tis_active\x18\x06 \x01(\bR\bisActive\"R\n" +
	"\x14DeleteServiceRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x1b\n" +
	"\tbarber_id\x18\x02 \x01(\tR\bbarberId\"\xa2\x01\n" +
	"\x0fServiceResponse\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x05R\x05price\x12)\n" +
	"\x10duration_minutes\x18\x04 \x01(\x05R\x0fdurationMinutes\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActive\"\xc9\x02\n" +
	"\rScheduleEvent\x12\x1f\n" +
	"\vschedule_id\x18\x01 \x01(\tR\n" +
	"scheduleId\x12\x1b\n" +
	"\tbarber_id\x18\x02 \x01(\tR\bbarberId\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\tR\aendTime\x123\n" +
	"\vpart_of_day\x18\x06 \x01(\x0e2\x13.staff.v1.PartOfDayR\tpartOfDay\x12:\n" +
	"\n" +
	"event_type\x18\a \x01(\x0e2\x1b.staff.v1.ScheduleEventTypeR\teventType\x12;\n" +
	"\voccurred_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt*P\n" +
	"\tPartOfDay\x12\x1b\n" +
	"\x17PART_OF_DAY_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0ePART_OF_DAY_AM\x10\x01\x12\x12\n" +
	"\x0ePART_OF_DAY_PM\x10\x02*i\n" +
	"\x11ScheduleEventType\x12\x1e\n" +
	"\x1aSCHEDULE_EVENT_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14SCHEDULE_EVENT_ADDED\x10\x01\x12\x1a\n" +
	"\x16SCHEDULE_EVENT_DELETED\x10\x022\x99\b\n" +
	"\fStaffService\x128\n" +
	"\x05Login\x12\x16.staff.v1.LoginRequest\x1a\x17.staff.v1.LoginResponse\x129\n" +
	"\x06Logout\x12\x17.staff.v1.LogoutRequest\x1a\x16.google.protobuf.Empty\x12M\n" +
	"\fRefreshToken\x12\x1d.staff.v1.RefreshTokenRequest\x1a\x1e.staff.v1.RefreshTokenResponse\x12A\n" +
	"\tGetBarber\x12\x1a.staff.v1.GetBarberRequest\x1a\x18.staff.v1.BarberResponse\x12J\n" +
	"\vListBarbers\x12\x1c.staff.v1.ListBarbersRequest\x1a\x1d.staff.v1.ListBarbersResponse\x12J\n" +
	"\vGetSchedule\x12\x1c.staff.v1.GetScheduleRequest\x1a\x1d.staff.v1.GetScheduleResponse\x12H\n" +
	"\x0eUpsertSchedule\x12\x1f.staff.v1.UpsertScheduleRequest\x1a\x15.staff.v1.ScheduleDay\x12_\n" +
	"\x12UpsertWeekSchedule\x12#.staff.v1.UpsertWeekScheduleRequest\x1a$.staff.v1.UpsertWeekScheduleResponse\x12I\n" +
	"\x0eDeleteSchedule\x12\x1f.staff.v1.DeleteScheduleRequest\x1a\x16.google.protobuf.Empty\x12D\n" +
	"\n" +
	"GetService\x12\x1b.staff.v1.GetServiceRequest\x1a\x19.staff.v1.ServiceResponse\x12M\n" +
	"\fListServices\x12\x1d.staff.v1.ListServicesRequest\x1a\x1e.staff.v1.ListServicesResponse\x12J\n" +
	"\rCreateService\x12\x1e.staff.v1.CreateServiceRequest\x1a\x19.staff.v1.ServiceResponse\x12J\n" +
	"\rUpdateService\x12\x1e.staff.v1.UpdateServiceRequest\x1a\x19.staff.v1.ServiceResponse\x12G\n" +
	"\rDeleteService\x12\x1e.staff.v1.DeleteServiceRequest\x1a\x16.google.protobuf.EmptyBBZ@github.com/RomanKovalev007/barber_crm/api/proto/staff/v1;staffv1b\x06proto3"

var (
	file_proto_staff_v1_staff_proto_rawDescOnce sync.Once
	file_proto_staff_v1_staff_proto_rawDescData []byte
)

func file_proto_staff_v1_staff_proto_rawDescGZIP() []byte {
	file_proto_staff_v1_staff_proto_rawDescOnce.Do(func() {
		file_proto_staff_v1_staff_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_staff_v1_staff_proto_rawDesc), len(file_proto_staff_v1_staff_proto_rawDesc)))
	})
	return file_proto_staff_v1_staff_proto_rawDescData
}

var file_proto_staff_v1_staff_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_staff_v1_staff_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_proto_staff_v1_staff_proto_goTypes = []any{
	(PartOfDay)(0),                     // 0: staff.v1.PartOfDay
	(ScheduleEventType)(0),             // 1: staff.v1.ScheduleEventType
	(*LoginRequest)(nil),               // 2: staff.v1.LoginRequest
	(*LoginResponse)(nil),              // 3: staff.v1.LoginResponse
	(*LogoutRequest)(nil),              // 4: staff.v1.LogoutRequest
	(*RefreshTokenRequest)(nil),        // 5: staff.v1.RefreshTokenRequest
	(*RefreshTokenResponse)(nil),       // 6: staff.v1.RefreshTokenResponse
	(*GetBarberRequest)(nil),           // 7: staff.v1.GetBarberRequest
	(*BarberResponse)(nil),             // 8: staff.v1.BarberResponse
	(*ListBarbersRequest)(nil),         // 9: staff.v1.ListBarbersRequest
	(*ListBarbersResponse)(nil),        // 10: staff.v1.ListBarbersResponse
	(*ScheduleDay)(nil),                // 11: staff.v1.ScheduleDay
	(*GetScheduleRequest)(nil),         // 12: staff.v1.GetScheduleRequest
	(*GetScheduleResponse)(nil),        // 13: staff.v1.GetScheduleResponse
	(*UpsertScheduleRequest)(nil),      // 14: staff.v1.UpsertScheduleRequest
	(*UpsertWeekScheduleRequest)(nil),  // 15: staff.v1.UpsertWeekScheduleRequest
	(*UpsertWeekScheduleResponse)(nil), // 16: staff.v1.UpsertWeekScheduleResponse
	(*DeleteScheduleRequest)(nil),      // 17: staff.v1.DeleteScheduleRequest
	(*GetServiceRequest)(nil),          // 18: staff.v1.GetServiceRequest
	(*ListServicesRequest)(nil),        // 19: staff.v1.ListServicesRequest
	(*ListServicesResponse)(nil),       // 20: staff.v1.ListServicesResponse
	(*CreateServiceRequest)(nil),       // 21: staff.v1.CreateServiceRequest
	(*UpdateServiceRequest)(nil),       // 22: staff.v1.UpdateServiceRequest
	(*DeleteServiceRequest)(nil),       // 23: staff.v1.DeleteServiceRequest
	(*ServiceResponse)(nil),            // 24: staff.v1.ServiceResponse
	(*ScheduleEvent)(nil),              // 25: staff.v1.ScheduleEvent
	(*timestamppb.Timestamp)(nil),      // 26: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),              // 27: google.protobuf.Empty
}
var file_proto_staff_v1_staff_proto_depIdxs = []int32{
	8,  // 0: staff.v1.LoginResponse.barber:type_name -> staff.v1.BarberResponse
	24, // 1: staff.v1.BarberResponse.services:type_name -> staff.v1.ServiceResponse
	8,  // 2: staff.v1.ListBarbersResponse.barbers:type_name -> staff.v1.BarberResponse
	0,  // 3: staff.v1.ScheduleDay.part_of_day:type_name -> staff.v1.PartOfDay
	11, // 4: staff.v1.GetScheduleResponse.days:type_name -> staff.v1.ScheduleDay
	0,  // 5: staff.v1.UpsertScheduleRequest.part_of_day:type_name -> staff.v1.PartOfDay
	14, // 6: staff.v1.UpsertWeekScheduleRequest.days:type_name -> staff.v1.UpsertScheduleRequest
	11, // 7: staff.v1.UpsertWeekScheduleResponse.days:type_name -> staff.v1.ScheduleDay
	24, // 8: staff.v1.ListServicesResponse.services:type_name -> staff.v1.ServiceResponse
	0,  // 9: staff.v1.ScheduleEvent.part_of_day:type_name -> staff.v1.PartOfDay
	1,  // 10: staff.v1.ScheduleEvent.event_type:type_name -> staff.v1.ScheduleEventType
	26, // 11: staff.v1.ScheduleEvent.occurred_at:type_name -> google.protobuf.Timestamp
	2,  // 12: staff.v1.StaffService.Login:input_type -> staff.v1.LoginRequest
	4,  // 13: staff.v1.StaffService.Logout:input_type -> staff.v1.LogoutRequest
	5,  // 14: staff.v1.StaffService.RefreshToken:input_type -> staff.v1.RefreshTokenRequest
	7,  // 15: staff.v1.StaffService.GetBarber:input_type -> staff.v1.GetBarberRequest
	9,  // 16: staff.v1.StaffService.ListBarbers:input_type -> staff.v1.ListBarbersRequest
	12, // 17: staff.v1.StaffService.GetSchedule:input_type -> staff.v1.GetScheduleRequest
	14, // 18: staff.v1.StaffService.UpsertSchedule:input_type -> staff.v1.UpsertScheduleRequest
	15, // 19: staff.v1.StaffService.UpsertWeekSchedule:input_type -> staff.v1.UpsertWeekScheduleRequest
	17, // 20: staff.v1.StaffService.DeleteSchedule:input_type -> staff.v1.DeleteScheduleRequest
	18, // 21: staff.v1.StaffService.GetService:input_type -> staff.v1.GetServiceRequest
	19, // 22: staff.v1.StaffService.ListServices:input_type -> staff.v1.ListServicesRequest
	21, // 23: staff.v1.StaffService.CreateService:input_type -> staff.v1.CreateServiceRequest
	22, // 24: staff.v1.StaffService.UpdateService:input_type -> staff.v1.UpdateServiceRequest
	23, // 25: staff.v1.StaffService.DeleteService:input_type -> staff.v1.DeleteServiceRequest
	3,  // 26: staff.v1.StaffService.Login:output_type -> staff.v1.LoginResponse
	27, // 27: staff.v1.StaffService.Logout:output_type -> google.protobuf.Empty
	6,  // 28: staff.v1.StaffService.RefreshToken:output_type -> staff.v1.RefreshTokenResponse
	8,  // 29: staff.v1.StaffService.GetBarber:output_type -> staff.v1.BarberResponse
	10, // 30: staff.v1.StaffService.ListBarbers:output_type -> staff.v1.ListBarbersResponse
	13, // 31: staff.v1.StaffService.GetSchedule:output_type -> staff.v1.GetScheduleResponse
	11, // 32: staff.v1.StaffService.UpsertSchedule:output_type -> staff.v1.ScheduleDay
	16, // 33: staff.v1.StaffService.UpsertWeekSchedule:output_type -> staff.v1.UpsertWeekScheduleResponse
	27, // 34: staff.v1.StaffService.DeleteSchedule:output_type -> google.protobuf.Empty
	24, // 35: staff.v1.StaffService.GetService:output_type -> staff.v1.ServiceResponse
	20, // 36: staff.v1.StaffService.ListServices:output_type -> staff.v1.ListServicesResponse
	24, // 37: staff.v1.StaffService.CreateService:output_type -> staff.v1.ServiceResponse
	24, // 38: staff.v1.StaffService.UpdateService:output_type -> staff.v1.ServiceResponse
	27, // 39: staff.v1.StaffService.DeleteService:output_type -> google.protobuf.Empty
	26, // [26:40] is the sub-list for method output_type
	12, // [12:26] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_staff_v1_staff_proto_init() }
func file_proto_staff_v1_staff_proto_init() {
	if File_proto_staff_v1_staff_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_staff_v1_staff_proto_rawDesc), len(file_proto_staff_v1_staff_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_staff_v1_staff_proto_goTypes,
		DependencyIndexes: file_proto_staff_v1_staff_proto_depIdxs,
		EnumInfos:         file_proto_staff_v1_staff_proto_enumTypes,
		MessageInfos:      file_proto_staff_v1_staff_proto_msgTypes,
	}.Build()
	File_proto_staff_v1_staff_proto = out.File
	file_proto_staff_v1_staff_proto_goTypes = nil
	file_proto_staff_v1_staff_proto_depIdxs = nil
}
